### ISSUE TITLE
error for ios 10 above?

### ISSUE THREAD

**Issue by fukemy** [kvyatkovskys/KVKCalendar#102]
hi, can u provice new pod to clear this error:

![Screen Shot 2020-10-29 at 11 48 04](https://user-images.githubusercontent.com/8202437/97526901-b11e8900-19dc-11eb-9b25-cb731ad32edb.png)

**Comment by kvyatkovskys** [comment]
Hello

What version do you use in your project?

**Comment by fukemy** [comment]
hi bro, im using xcode 12.1 and target build 11.0

**Comment by kvyatkovskys** [comment]
hmm, I'll check this, thank you

**Comment by fukemy** [comment]
thanks
