### ISSUE TITLE
change month and year background color

### ISSUE THREAD

**Issue by fukemy** [kvyatkovskys/KVKCalendar#103]
hi, thanks for great lib after first time used. I tried to change background to dark like my application did. But i can not find the property for change month/year color. Can u help?

![Screen Shot 2020-10-29 at 14 00 07](https://user-images.githubusercontent.com/8202437/97536094-37dc6180-19ef-11eb-899d-60008f04eb3e.png)
![Screen Shot 2020-10-29 at 14 00 10](https://user-images.githubusercontent.com/8202437/97536104-3c087f00-19ef-11eb-89cd-292fb37c16f0.png)
![Screen Shot 2020-10-29 at 14 00 13](https://user-images.githubusercontent.com/8202437/97536107-3d39ac00-19ef-11eb-8eed-3faa2f4ead39.png)
![Screen Shot 2020-10-29 at 14 00 15](https://user-images.githubusercontent.com/8202437/97536110-3dd24280-19ef-11eb-945c-5b07439932be.png)

**Comment by fukemy** [comment]
i tried to change header of month, do u remember the property? 
![Screen Shot 2020-10-29 at 14 18 02](https://user-images.githubusercontent.com/8202437/97537559-90acf980-19f1-11eb-97c9-efac9006906b.png)

**Comment by fukemy** [comment]
ok i first i got fixed for month
```
private lazy var headerView: WeekHeaderView = {
        let height: CGFloat
        if style.month.isHiddenTitleDate {
            height = style.month.heightHeaderWeek
        } else {
            height = style.month.heightHeaderWeek + style.month.heightTitleDate
        }
        let view = WeekHeaderView(frame: CGRect(x: 0, y: 0, width: frame.width, height: height), style: style)
        view.backgroundColor = style.week.colorBackground
        return view
    }()
```

**Comment by kvyatkovskys** [comment]
thx man 🙂

try this `style.week.colorBackground`

**Comment by fukemy** [comment]
hmm, i think u need to provide the color of titleLabel for WeekheaderView, because it does not have setTextColor
``` final class WeekHeaderView: UIView {
private lazy var titleLabel: UILabel = {
        let label = UILabel()
        label.textAlignment = style.month.titleDateAligment
        label.font = style.month.fontTitleDate
        label.tag = -999
        return label
    }()
```
