### ISSUE TITLE
How to change locale in library?

### ISSUE THREAD

**Issue by yevgeniyzhigadlov** [kvyatkovskys/KVKCalendar#109]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kvyatkovskys** [comment]
Hello!

You need to set `style.locale = Locale(identifier: "fr_FR")` for example. But now it doesn't work. I'll fix it in the next version `0.4.2`
