### ISSUE TITLE
My eventtext is not visible

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#111]
I have assigned my data to event model but after assigning it text is not visible.I have created custom view and getting upper height.
![IMG_710E38B8215B-1](https://user-images.githubusercontent.com/20422528/100602266-af244e80-3329-11eb-87f7-010c40db36a7.jpeg)

**Comment by kvyatkovskys** [comment]
Hello

could you send your code? How do you call init for `CustomViewEvent`?

**Comment by learnasucan** [comment]
Hi ,


Thanks for your reply.I am sending my code to you.

import UIKit
import KVKCalendar


class KVKLibVC: UIViewController {

    // MARK: - Getting current month in string and other date formats
    var currentMonth: String = getMonthOnlyFromDate.string(from: Date())
    var currentYear: String = getYearOnlyFromDate.string(from: Date())

    var eventsForMonth: [EventModel] = []
    var today: Date = Date()
    var events = [Event]()

   @IBOutlet weak var calendatViewNew: UIView! //created view and added
your calendar view

    private var selectDate: Date = KVKLibraryFormat.date(from:
Date().convertToString("dd.MM.yyyy"))!

    private lazy var calendarUIView: CalendarView = {
        let calendar = CalendarView(frame: calendatViewNew.frame , date:
selectDate, style: style)

        calendar.delegate = self
        calendar.dataSource = self
        return calendar
    }()

    private var style: Style = {
        var style = Style()
        if UIDevice.current.userInterfaceIdiom == .phone {
            style.timeline.widthTime = 50 // Left column which separate
events
            style.timeline.currentLineHourWidth = 50 //current time box
width
            style.timeline.offsetTimeX = 2
            style.timeline.heightLine = 2 // separator line height
            style.timeline.separatorLineColor = #colorLiteral(red:
0.3333333433, green: 0.3333333433, blue: 0.3333333433, alpha: 1)

            //            style.event.colorStubView = #colorLiteral(red:
0.9607843161, green: 0.7058823705, blue: 0.200000003, alpha: 1)
            //            style.allDay.isPinned = false // after scroll it
moves inside
            style.allDay.height = 25
            style.allDay.offsetHeight = 20
//            style.allDay.backgroundColor = #colorLiteral(red: 1, green:
1, blue: 1, alpha: 1)
//            style.allDay.titleColor = #colorLiteral(red: 1, green: 1,
blue: 1, alpha: 1) //all-day color

            style.timeline.offsetLineLeft = 2
            style.headerScroll.titleDateAligment = .center
            style.headerScroll.isAnimateTitleDate = false
            style.headerScroll.heightHeaderWeek = 70
            style.headerScroll.colorBackground = #colorLiteral(red:
0.9519069791, green: 0.4668239951, blue: 0.2027148902, alpha: 1)
            style.headerScroll.isHiddenSubview = false

            style.event.isEnableVisualSelect = false
            style.month.isHiddenTitle = false
            style.timeline.timeColor = #colorLiteral(red: 0, green: 0,
blue: 0, alpha: 1)

        } else {
            style.timeline.widthEventViewer = 0
            style.headerScroll.fontDate = .systemFont(ofSize: 17)
            style.headerScroll.fontNameDay = .systemFont(ofSize: 17)
        }
        style.startWeekDay = .monday
        style.timeSystem = TimeHourSystem.currentSystemOnDevice ?? .twelve
        if #available(iOS 13.0, *) {
            style.event.iconFile = UIImage(systemName: "paperclip")
        }
        return style
    }()

    override func viewDidLoad() {
        super.viewDidLoad()
//I am loading data here from firestore
        loadEventsForSpecificMonth(for: currentMonth, for: currentYear)
        print(eventsForMonth)


        self.calendatViewNew.addSubview(calendarUIView)

        self.createEvents { [weak self] (events) in
            DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
                self?.events = events
                self?.calendarUIView.reloadData()
            }
        }
        // Do any additional setup after loading the view.
    }

    @IBAction func backAction(_ sender: UIButton) {
        self.navigationController?.popViewController(animated: true)
    }

    func loadEventsForSpecificMonth(for month: String, for year: String) {
       //API to collect data in sanpshot
        let listener = eventCollectionRef
            .order(by: Constants.Event.dateAdded)
            .whereField(Constants.Event.month, isEqualTo: month)
            .whereField(Constants.Event.isVisibleToParent, isEqualTo: true)
            .whereField(Constants.Event.isDeleted, isEqualTo: false)
            .addSnapshotListener { (querySnapshot, error) in
                guard let snapshotDocuments = querySnapshot?.documents else
{
                    print("Error retrieving event data for
month:\(error!.localizedDescription)")
                    return
                }
                self.eventsForMonth = snapshotDocuments.compactMap({
(queryDocumentSnapshot) -> EventModel? in
                    return try? queryDocumentSnapshot.data(as:
EventModel.self)
                })

         // here data filled inside events array
                self.createEvents { [weak self] (events) in
                    DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
                        self?.events = events
                        self?.calendarUIView.reloadData()
                    }
                }

        }
        FirestoreReferenceManager.listeners.append(listener)
    }


}

extension KVKLibVC {
    func createEvents(completion: ([Event]) -> Void) {

        // Get events from storage / API

        let eventsNew = eventsForMonth.compactMap { (item) -> Event in

            let startDate = item.date
            let endDate = item.endDate ?? Date()
            let startTime = item.dateString

            let endTime = item.endTimeString ?? ""
            var event = Event(ID: item.eventId)

            event.start = startDate // start date event
            event.end = endDate
            event.color = EventColor(#colorLiteral(red: 0.05882352963,
green: 0.180392161, blue: 0.2470588237, alpha: 1))
//            event.backgroundColor = #colorLiteral(red: 0.9529411793,
green: 0.6862745285, blue: 0.1333333403, alpha: 1)
//            event.textColor = #colorLiteral(red: 0.4392156899, green:
0.01176470611, blue: 0.1921568662, alpha: 1)
            event.isAllDay = false
            event.isContainsFile = true
            event.recurringType = .everyDay// recurring even
            event.text = "\(item.description)"
            event.textForMonth = "\(item.createdBy)"
            return event
        }

        completion(eventsNew)
    }

    func timeFormatter(date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = style.timeSystem.format
        return formatter.string(from: date)
    }

    func formatter(date: String) -> Date {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ"
        return formatter.date(from: date) ?? Date()
    }
}

final class CustomViewEvent: EventViewGeneral {
    override init(style: Style, event: Event, frame: CGRect) {
        super.init(style: style, event: event, frame: frame)

        let imageView = UIImageView(image: UIImage(named: "ic_stub"))
        imageView.frame = CGRect(origin: CGPoint(x: 3, y: 1), size:
CGSize(width: frame.width - 6, height: frame.height - 2))
        imageView.contentMode = .scaleAspectFit
        addSubview(imageView)
        backgroundColor = event.backgroundColor
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

extension KVKLibVC: CalendarDataSource {
    func eventsForCalendar() -> [Event] {
        return events
    }

    // optional function from CalendarDataSource
    func willDisplayEventView(_ event: Event, frame: CGRect, date: Date?)
-> EventViewGeneral? {
        //        guard event.ID == id else { return nil }

        return CustomViewEvent(style: style, event: event, frame: frame)
    }

    func dequeueDateCell(date: Date?, type: CalendarType, collectionView:
UICollectionView, indexPath: IndexPath) -> UICollectionViewCell? {
        let cell = collectionView.dequeueCell(indexPath: indexPath) {
(cell: CustomDayCell) in
            cell.imageView.image = #imageLiteral(resourceName:
"ptab_launch")
        }

        if type == .year, date?.month == Date().month {
            return cell
        } else if date?.day == Date().day {
            return cell
        } else {
            return nil
        }
    }
}



extension KVKLibVC: CalendarDelegate {
    // get a selecting date
    func didSelectDate(_ date: Date?, type: CalendarType, frame: CGRect?) {}
    // get a selecting event
    func didSelectEvent(_ event: Event, type: CalendarType, frame: CGRect?)
{}
    // tap on more fro month view
    func didSelectMore(_ date: Date, frame: CGRect?) {}
    // event's viewer for iPad
    func eventViewerFrame(_ frame: CGRect) {}
    // drag & drop events
    func didChangeEvent(_ event: Event, start: Date?, end: Date?) {}
    // tap on timeline or month cell
    func didAddNewEvent(_ event: Event, _ date: Date?) {}
    // get current displaying events
    func didDisplayEvents(_ events: [Event], dates: [Date?]) {}
    // get next date when the calendar scrolls (works for month view)
    func willSelectDate(_ date: Date, type: CalendarType) {}
}

final class CustomDayCell: UICollectionViewCell {

    let imageView: UIImageView = {
        let view = UIImageView()
        view.contentMode = .scaleAspectFit
        return view
    }()

    override init(frame: CGRect) {
        super.init(frame: frame)
        imageView.frame = CGRect(origin: .zero, size: frame.size)
        contentView.addSubview(imageView)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

final class EventViewer: UIView {
    private let textLabel: UILabel = {
        let label = UILabel()
        label.font = .systemFont(ofSize: 19)
        label.textAlignment = .center
        label.numberOfLines = 0
        label.text = "Testing event to view the description"
        return label
    }()

    private let lineView: UIView = {
        let view = UIView()
        if #available(iOS 13.0, *) {
            view.backgroundColor = .systemGray3
        } else {
            view.backgroundColor = .lightGray
        }
        return view
    }()

    var text: String? {
        didSet {
            textLabel.text = text
        }
    }

    override init(frame: CGRect) {
        super.init(frame: frame)
        if #available(iOS 13.0, *) {
            backgroundColor = .systemBackground
        } else {
            backgroundColor = .white
        }
        addSubview(textLabel)
        addSubview(lineView)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    func reloadFrame(frame: CGRect) {
        textLabel.frame = frame
        lineView.frame = CGRect(origin: .zero, size: CGSize(width: 1,
height: frame.height))
    }
}


*Thanks ,*

*Prachit *

**Comment by kvyatkovskys** [comment]
If you don’t use a custom view for Event you need to delete this method `willDisplayEventView(_ event: Event, frame: CGRect, date: Date?)` or you have to change class `CustomEventView` as you want. Add a UILabel instead UIImageView for example. And I guess, you have not an image with name `ic_stub` in your project.

**Comment by kvyatkovskys** [comment]
And you need to delete this `DispatchQueue.main.asyncAfter(deadline: .now() + 3) { ` this the line only for testing (simulation of delay from the backend)

**Comment by learnasucan** [comment]
Thanks a lot.

Text issue solved. But if I want to limit the width of the timebox and
modify it .What will be the way?  now you have adjusted as per event
occurrences and width gets modified accordingly.For one event it occupies
the whole width of the screen.for two events half width allocated to both
events and so on. If I want to give fixed width and want to change the look
of the background what will be the way?

**Comment by kvyatkovskys** [comment]
YW 🙂

So yes, you need to use a custom event view. But u can't set fixed width for an event at timeline🤔 perhaps, need to add a new property.

**Comment by learnasucan** [comment]
event.textForMonth is not visible in same case

**Comment by kvyatkovskys** [comment]
Could you give a more details, pls? For me works fine for iPad

**Comment by learnasucan** [comment]
I want to modify day view and month view in this way .just let me know which class file whether I have to override or modify  to  apply such changes.
![Dayview](https://user-images.githubusercontent.com/20422528/101875650-fd9ade00-3bb0-11eb-924f-b44c11402390.png)
![monthView](https://user-images.githubusercontent.com/20422528/101937629-200c1600-3c08-11eb-9704-100a4db2ff12.png)

**Comment by kvyatkovskys** [comment]
sorry for long answer 🙂

for timeline on DayView/WeekView 

To use a custom view for specific event or date you need to create a new view of class EventViewGeneral and return the view in function.
class CustomViewEvent: EventViewGeneral {
    override init(style: Style, event: Event, frame: CGRect) {
        super.init(style: style, event: event, frame: frame)
    }
}

// optional function from CalendarDataSource
func willDisplayEventView(_ event: Event, frame: CGRect, date: Date?) -> EventViewGeneral? {
    guard event.ID == id else { return nil }
    return customEventView
}

**Comment by kvyatkovskys** [comment]
for MonthView

To use a custom date cell, just subscribe on this optional method from CalendarDataSourcse.

`func dequeueDateCell(date: Date?, type: CalendarType, collectionView: UICollectionView, indexPath: IndexPath) -> UICollectionViewCell? {    
    return collectionView.dequeueCell(indexPath: indexPath) { (cell: CustomDayCell) in
        configurate a cell
    }
}`

here `CustomDayCell ` your cell

**Comment by learnasucan** [comment]
Thanks for reply .I will try this .Cant we use calenderView on interface of xcode rather programmatically? I have tried this but calandarView closure having selectdate, frame and delegate is not available if I use Interface.One more select date is not varying if I have changed it using controls.What should I do?
I think you should provide on example for custom modification of each view  cells for day ,week , month , yearly view in both ways programmatically and using interface,So it might really helpful.

**Comment by learnasucan** [comment]
Hi @kvyatkovskys ,
I am trying to register my custom cell nib to the your collectionView but I did not find any way to register nib in your source code.
for example, 
`collectionView.register(UINib(nibName: "MyCell", bundle: .main), forCellWithReuseIdentifier: "mycell")`
Could you please let me know the solution for it?

**Comment by kvyatkovskys** [comment]
Hello, hmm 🤔
looks like we need to add an additional method to register a custom cell from nib

**Comment by learnasucan** [comment]
> Hello, hmm 🤔
> looks like we need to add an additional method to register a custom cell from nib

Why don't you add new example for customisation of cells in programatically as well as in interface?

**Comment by kvyatkovskys** [comment]
actually you can register your cell in this method
`func dequeueDateCell(date: Date?, type: CalendarType, collectionView: UICollectionView, indexPath: IndexPath) -> UICollectionViewCell? {}`

**Comment by learnasucan** [comment]
@kvyatkovskys , Hi thanks for updating me but I am getting error while creating own cell.
One issue I got 
`  func didSelectDate(_ date: Date?, type: CalendarType, frame: CGRect?) {}`
why this method calling again and again.
And also want to disable scrolling in monthview by touch.I have added manual functionality to change month by  using
` calendarView.set(type: .month, date: selectDate)`
[CalendarVC.docx](https://github.com/kvyatkovskys/KVKCalendar/files/5766158/CalendarVC.docx)
[DayVC.docx](https://github.com/kvyatkovskys/KVKCalendar/files/5766160/DayVC.docx)
[MonthVC.docx](https://github.com/kvyatkovskys/KVKCalendar/files/5766161/MonthVC.docx)
![ui](https://user-images.githubusercontent.com/20422528/103566584-3e53f180-4ee8-11eb-8579-3baa8b5f1aeb.png)
I am using two separate containerView for loading day view and monthView.Please suggest me on same my didSelectMethod calling again and again.I am unable to modify month and day cell
