### ISSUE TITLE
If I use updateDate method, didSelectDate method is getting called again and again.

### ISSUE THREAD

**Issue by ShrikantCW** [kvyatkovskys/KVKCalendar#119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ShrikantCW** [comment]
HI @kvyatkovskys , Im getting issue :  when I use func updateDate(newDate: Date?, calendar: Calendar = Calendar.current) -> Event? method below method didSelectDate is calling many times
func didSelectDate(_ date: Date?, type: CalendarType, frame: CGRect?) {}

**Comment by kvyatkovskys** [comment]
Hello 🙂
Interesting 🤔, thx for the response. I'll check.

**Comment by learnasucan** [comment]
Looking forward for the release.
