### ISSUE TITLE
Time like xx:59-xx:59 gets event frame height wrong

### ISSUE THREAD

**Issue by negovskiy** [kvyatkovskys/KVKCalendar#120]
**Describe the bug**
Like it is stated in title, event frame height is -1 when minutes set to 59.

**To Reproduce**
1. Create event with time 09:59-10:59
2. Open day or week timeline

**Expected behavior**
Event frame shoudd be calculated as usual

**Screenshots**
<img width="1094" alt="Screen Shot 2021-01-06 at 2 44 24 PM" src="https://user-images.githubusercontent.com/1741944/103770054-0b1b7a80-502e-11eb-9d09-5ad7bbd27e3a.png">

**Comment by kvyatkovskys** [comment]
Thx for the issue. I'll check it 🙂
