### ISSUE TITLE
can we use internal collectionView of monthVIew in myviewController?

### ISSUE THREAD

**Issue by prachit1105** [kvyatkovskys/KVKCalendar#121]
I want to stop scrolling in month view by touching up and down , for that I have used update method of event to increment or decrement month of selectedDate.
I just want to use like calendarView.monthView.collectionView.isScrollEnabled = false,
Basically I am not able use your internal variables and methods directly because it is in pod.
So is there any way to access those ?

**Comment by kvyatkovskys** [comment]
Need to add an additional property to `MonthStyle`. Feel free to create a PR I'll review it or wait the next version 🙂

**Comment by prachit1105** [comment]
Thanks @kvyatkovskys,
I really appreciate for your work hope your new version will be released soon.One more why didSelectmethod gets called after calling update method of event ?

**Comment by kvyatkovskys** [comment]
Perhaps, this is a bug. I'll check.

**Comment by kvyatkovskys** [comment]
Hello.
Added a new property to `MonthStyle` and a new method `func willDisplayCollectionView(frame: CGRect, type: CalendarType) -> UICollectionView?` to ability use your own `collection view`
