### ISSUE TITLE
Extra dates are coming after my current month and next months in monthView

### ISSUE THREAD

**Issue by ShrikantCW** [kvyatkovskys/KVKCalendar#122]
![Screenshot 2021-01-07 at 7 33 40 PM](https://user-images.githubusercontent.com/60424873/103908658-b7da2280-5128-11eb-99f1-1973a40dc849.png)
Please look into this issue, and also somewhere I found that firstDate of month is not coming after using updateCalendar method. Please help me out.

**Comment by kvyatkovskys** [comment]
thx for the response. I'll check 👍🏼

**Comment by kvyatkovskys** [comment]
`firstDate of month is not coming after using updateCalendar method` Could you give a more details, pls?
