### ISSUE TITLE
negative sizes are not supported in the flow layout

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#123]
**Describe the bug**
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'negative sizes are not supported in the flow layout' after updating pod

**To Reproduce**
1. Go to Month View which I have created
2. See error

**Expected behavior**
Normal Month view seen as per old version 0.4.1.

**Comment by kvyatkovskys** [comment]
Could you send a more details, pls? Which version do you use? 

For me works fine ver. 0.4.5

**Comment by learnasucan** [comment]
Thanks,
I have used  ` calendarView.set(type: .month, date: selectDate)` to update month calendar.
First I have used this library of version 0.4.1 , its working fine .After that I have updated this library to 0.4.5.Now this error is coming regarding collectionview.Basically I have used your collection view in programaticaly.

**Comment by kvyatkovskys** [comment]
Do you use this method `func sizeForCell(_ date: Date?, type: CalendarType) -> CGSize?` in your code?

**Comment by kvyatkovskys** [comment]
What do you use `style.month.scrollDirection` and frame for calendarView?

**Comment by learnasucan** [comment]
> Do you use this method `func sizeForCell(_ date: Date?, type: CalendarType) -> CGSize?` in your code?

no, I have not implemented this.Default way I have used here

**Comment by learnasucan** [comment]
> What do you use `style.month.scrollDirection` and frame for calendarView?

I have not used  `style.month.scrollDirection` as its default is vertical so kept as it is.
For reloading frame I have  override didlayout method as you kept.
```
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        var frame = view.frame
        frame.origin.y = 0
        calendarView.reloadFrame(frame)
    }
```

**Comment by kvyatkovskys** [comment]
Could you print `frame` before calling this function `calendarView.reloadFrame()`?

**Comment by kvyatkovskys** [comment]
I'm interested in size 🤔

**Comment by learnasucan** [comment]
> I'm interested in size 🤔
`calendarView.reloadFrame()`
This method is not getting called when I am selecting month case.
First time when default screen  loaded it shows 
```
 (0.0, 0.0, 793.0, 638.0)
  ▿ origin : (0.0, 0.0)
    - x : 0.0
    - y : 0.0
  ▿ size : (793.0, 638.0)
    - width : 793.0
    - height : 638.0
```

but after that 
```
 (0.0, 0.0, 0.0, 0.0)
  ▿ origin : (0.0, 0.0)
    - x : 0.0
    - y : 0.0
  ▿ size : (0.0, 0.0)
    - width : 0.0
    - height : 0.0

```

**Comment by kvyatkovskys** [comment]
Thx, I'll fix the crash in the next version 🙂

**Comment by learnasucan** [comment]
Thanks for your effort.But couldn't get why did this happen? Can you explain, please?

**Comment by kvyatkovskys** [comment]
![image](https://user-images.githubusercontent.com/8233076/104431482-fe9ca200-5598-11eb-9561-b82d49a1b0e2.jpeg)

I try to add a small offset (0.2) but the width = 0
