### ISSUE TITLE
In month view date range is inconsistent

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#124]
**Describe the bug**
DATE range is inconsistent 

**To Reproduce**
1. Go to monthview
2. after clicking on manual button `calendarView.set(type: .month, date: selectDate)` gets called
3. Scroll down to particular month 
4. See error **Screenshots**

![Screenshot 2021-01-13 at 10 56 58 PM](https://user-images.githubusercontent.com/20422528/104487593-4f40e900-55f3-11eb-8134-928d89af7560.png)

**Expected behavior**
consistent date

**Comment by kvyatkovskys** [comment]
Try to disable the property `public var showDatesForOtherMonths` and check again, pls

**Comment by learnasucan** [comment]
Thanks dear, It works

**Comment by kvyatkovskys** [comment]
Cool, I'll fix the feature in the next versions.

**Comment by learnasucan** [comment]
Need to rectify this white space.

![extra space](https://user-images.githubusercontent.com/20422528/104583422-1a7e7180-5687-11eb-8edf-ae58d38693fc.jpg)

As you seen in the image,  I have updated month for feb using this `calendarView.set(type: .month, date: selectDate)` but  calendar view moves to the 7th feb 2021. so basically I have to scroll manually to see 1st feb `2021`
