### ISSUE TITLE
Fatal error: Can't form Range with upperBound < lowerBound

### ISSUE THREAD

**Issue by ShrikantCW** [kvyatkovskys/KVKCalendar#125]
**Describe the bug**
When I'm loading month view got an error and screen stuck :
Fatal error: Can't form Range with upperBound < lowerBound 

in the function : private func calculateCrossEvents(_ events: [Event]) -> [TimeInterval: CrossEvent] 
file : TimelineView.swift 

**To Reproduce**
1. Go to  Monthview
 

**Expected behavior**

Loading events in month view

**Screenshots**

![Screenshot 2021-01-14 at 12 57 54 PM](https://user-images.githubusercontent.com/60424873/104557994-21e25280-5668-11eb-901b-f5022f800c91.png)
![Screenshot 2021-01-14 at 11 03 04 AM](https://user-images.githubusercontent.com/60424873/104682261-45fe6c00-571a-11eb-812f-deda45ec2192.png)

**Comment by kvyatkovskys** [comment]
🤔 could you send list of events, pls? (ex. json file)

**Comment by prachit1105** [comment]
> **Describe the bug**
> When I'm loading month view got an error and screen stuck :
> Fatal error: Can't form Range with upperBound < lowerBound
> 
> in the function : private func calculateCrossEvents(_ events: [Event]) -> [TimeInterval: CrossEvent]
> file : TimelineView.swift
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to  Monthview
> 
> **Expected behavior**
> 
> Loading events in month view
> 
> **Screenshots**
> 
> ![Screenshot 2021-01-14 at 12 57 54 PM](https://user-images.githubusercontent.com/60424873/104557994-21e25280-5668-11eb-901b-f5022f800c91.png)
> ![Screenshot 2021-01-14 at 11 03 04 AM](https://user-images.githubusercontent.com/60424873/104682261-45fe6c00-571a-11eb-812f-deda45ec2192.png)

you can do 

```

let startDate = item.starDate
            
            if let endDate = item.endDate, let end = Calendar.current.date(byAdding: .minute, value: 30, to: endDate) {
                if startDate >= endDate {
                    event.end = end
                } else {
                    event.end = endDate
                }
            }
event.start = startDate 

```

**Comment by ZimiHome** [comment]
I have the same issue. The problem is if you not set start and date to Event object ( i used Event(ID: "1"))

**Comment by rockyftn** [comment]
I have the same issue. The problem is if you not set start and end date to Event object. I used Event(ID: "1") and got these crash
