### ISSUE TITLE
Need to rectify this white space.

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#126]
Need to rectify this white space.

![extra space](https://user-images.githubusercontent.com/20422528/104583422-1a7e7180-5687-11eb-8edf-ae58d38693fc.jpg)

As you seen in the image,  I have updated month for feb using this `calendarView.set(type: .month, date: selectDate)` but  calendar view moves to the 7th feb 2021. so basically I have to scroll manually to see 1st feb `2021`

_Originally posted by @learnasucan in https://github.com/kvyatkovskys/KVKCalendar/issues/124#issuecomment-760130468_

**Comment by kvyatkovskys** [comment]
Thx for the issue. I'll fix in the version.
