### ISSUE TITLE
Show the day

### ISSUE THREAD

**Issue by yugochen** [kvyatkovskys/KVKCalendar#127]
I dont show customCell,
How do show the day or month

my code is no work

func dequeueDateCell(date: Date?, type: CalendarType, collectionView: UICollectionView, indexPath: IndexPath) -> UICollectionViewCell? {
        let cell = collectionView.dequeueCell(indexPath: indexPath) { (cell: CustomDayCell) in
            
        }
        
        switch type {
        case .year where date?.month == Date().month:
            return cell
        case .year where date?.month != Date().month:
            return cell
        case .day, .week, .month:
            guard date?.day == Date().day else { return cell }
            return cell
        default:
            return nil
        }
    }

**Comment by kvyatkovskys** [comment]
Hello 🙂
If you wanna to show a default cell you need to delete the method.

**Comment by learnasucan** [comment]
> Hello 🙂
> If you wanna to show a default cell you need to delete the method.

which method? dequeDate cell?

**Comment by kvyatkovskys** [comment]
correct `dequeueDateCell`
