### ISSUE TITLE
Month view swipe to incorrect months index when changing startWeekDay

### ISSUE THREAD

**Issue by vinhnx** [kvyatkovskys/KVKCalendar#129]
**Describe the bug**
Month view swipe to incorrect months index when changing `startWeekDay` from `Style`. For example: change the `startWeekDay` attribute of `Style` to a custom day, in this case, `.monday`

**To Reproduce**
1. change the `startWeekDay` attribute of `Style` to another day rather than `.sunday`
2. Swipe month view back and forth
3. Check the header date
4. It shows incorrect month

**Expected behavior**
It should show correct month index when changing the `startWeekDay` attribute of `Style`.

**Screenshots**
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-18 at 16 06 45](https://user-images.githubusercontent.com/1097578/104894774-b1a93900-59a7-11eb-8ff5-18cce8701fd2.png)

**Additional context**
Check the provided example project, in `ViewController`, change:
```swift
style.startWeekDay = .monday
```
then run, choose "Month" segment, swipe back and forth several months => The month page index is strange when changing the `startWeekDay`

---

Thanks for this awesome library, btw, keep up the good work!

**Comment by kvyatkovskys** [comment]
thx for the issue... I'll check this 🙂
