### ISSUE TITLE
Move Events from Timeline or Week week

### ISSUE THREAD

**Issue by StarkSoftware** [kvyatkovskys/KVKCalendar#13]
Hi, I wanted to know if you had thought or taken into consideration the possibility of moving appointments directly from the timeline or weekview as the original apple calendar. Or if you plan to extend the period directly from the event to the timeline or weekview with the longtap gesture.

Congratulations for the library

**Comment by kvyatkovskys** [comment]
Hey, thx)
Yes, I plan to do this in future. I'll try to do as in the original apple calendar. 
Now I finish fixing bugs with timeline, year and month calendar.
