### ISSUE TITLE
can we have single text label instead 3 text label if more than three events are there?

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#131]
**Is your feature request related to a problem? Please describe.**
Actually I was trying to add events in month view. I have used your library .I found it is very useful.But on month view there were 3 text label with more text is included.

**Describe the solution you'd like**
I want there only one single text label.
In that customization if any events are there then only one label with special symbol according to event will be presented
more word should be replaced with number of events like "5 my_text". my_ text is customized word

**Describe alternatives you've considered**
Then I have to remove textformonth property in month Style.Only blank text will set and more will be shown

**Additional context**
I think you should share customization way for month cell

![single text field](https://user-images.githubusercontent.com/20422528/105030078-416ae800-5a79-11eb-9083-87a3e6c660ec.png)

**Comment by kvyatkovskys** [comment]
You can use a `func dequeueDateCell(date: Date?, type: CalendarType, collectionView: UICollectionView, indexPath: IndexPath) -> UICollectionViewCell?` and add your own cell.

`switch type {
        case .month:
            return YourCustomCell()
        default:
            return nil
 }`

**Comment by learnasucan** [comment]
Thanks for your reply.
but one query regarding data which I want to place inside my custom cell is different .It will crash for multiple events on single day.So how can I modify cells to match your model event?

**Comment by kvyatkovskys** [comment]
I don't understand that you want 🙂
To use a custom cell you need implement the method `dequeueDateCell` or just return nil for a specific date or view
