### ISSUE TITLE
Can we disable add new event selection after selecting dayview timeline?

### ISSUE THREAD

**Issue by ShrikantCW** [kvyatkovskys/KVKCalendar#132]
**Is your feature request related to a problem? Please describe.**

Description:After clicking on day view timeline, Add new event view appear, but I don't want to add new event by touching timeline . I am trying to show only event.

**Describe the solution you'd like**
Style.timeline.addNewEvent = false

**Describe alternatives you've considered**
You can disable touch on day view by adding your property ( Means you can see events on timeline but you can't edit it after clicking on timeline)

**Comment by kvyatkovskys** [comment]
Good suggestion 👍🏻
I'll add a new property in the next version

**Comment by prachit1105** [comment]
> Good suggestion 👍🏻
> I'll add a new property in the next version

when can we expect next version

**Comment by kvyatkovskys** [comment]
the next version will release tomorrow. added a new property `style.timeline.isEnabledCreateNewEvent`

**Comment by ShrikantCW** [comment]
Thanks for the update. 🙂
