### ISSUE TITLE
Installing with CocoaPod results in build failure

### ISSUE THREAD

**Issue by bouchtaoui-dev** [kvyatkovskys/KVKCalendar#133]
## Bug description

MacOS Catalina
Xcode 11

### Issue
After I installed KVKCalendar with 'pod KVKCalendar' and #pod install, I get build error as follows:

<img width="213" alt="Screenshot 2021-01-21 at 12 40 46" src="https://user-images.githubusercontent.com/428598/105348985-5b2b3d00-5be9-11eb-9164-1bda2357de7b.png">

These seem UIPointer related stuff for iPad I guess. But I use my project only for iPhone.
How can I fix this?

**Comment by kvyatkovskys** [comment]
Hello🙂

This API is available on Xcode 12🤔
I guess, need to delete `UIPointer` from project

**Comment by bouchtaoui-dev** [comment]
Hi @kvyatkovskys ,

Thank you for your response.

I have my project set to **12.1**,
but the errors still remain, while these errors occur only on places where:
**@available(iOS 13.4, *)**

My project setting:
<img width="471" alt="Screenshot 2021-01-21 at 14 35 32" src="https://user-images.githubusercontent.com/428598/105358162-1a85f080-5bf6-11eb-950b-aebdb1543cc7.png">

Build error in KVKCalendar:
<img width="910" alt="Screenshot 2021-01-21 at 14 36 24" src="https://user-images.githubusercontent.com/428598/105358262-3be6dc80-5bf6-11eb-864f-e44e1037d1c8.png">

So since my target is set to 12.1, code that is marked as `@available(iOS 13.4, *)` should not be built, I assume.

Am I doing something wrong? I never had issues with installing pods and building them. But that was in the Obj-C era.

**Comment by kvyatkovskys** [comment]
This is a new API that works on Xcode 12 and above.

**Comment by bouchtaoui-dev** [comment]
Ok, I solved it by upgrading to Xcode 12, now it works.
Thnx.

**Comment by kvyatkovskys** [comment]
Cool 👍🏻
