### ISSUE TITLE
Compiling with SPM fails

### ISSUE THREAD

**Issue by fgeistert** [kvyatkovskys/KVKCalendar#134]
**Describe the bug**
When using SPM to integrate the framework, compiling fails.

**To Reproduce**
1. Clone using SPM (on branch `feature/v_0.4.6`)
2. Try to compile

**Expected behavior**
Compiling works.

**Screenshots**
![Image](https://user-images.githubusercontent.com/3149925/105350004-cd505180-5bea-11eb-9c00-e23d916c5cf5.png)

**Additional context**
Thanks for your awesome library! The fix is really easy, I am going to open a PR.

**Comment by fgeistert** [comment]
Pull Request is #135

**Comment by kvyatkovskys** [comment]
Hello 🙂

Yeah I know of this problem. `feature/v_0.4.6` branch is under development. Thx for your PR.
