### ISSUE TITLE
Header-scroll month date title is not set as you have shown in your screen?

### ISSUE THREAD

**Issue by prachit1105** [kvyatkovskys/KVKCalendar#136]
**Describe the bug**
I am not able set header date as you have shown for different views like month view ,day view, year view

**To Reproduce**
1. Go to upper segmentControl
2. Click on month or day
3. Date is not changed it is same as dayView 

**Expected behavior Screenshots**
![Screenshot 2021-01-21 at 7 21 55 PM](https://user-images.githubusercontent.com/68735569/105362156-8a10d580-5c20-11eb-80f1-d024ed354a13.png)
![Screenshot 2021-01-21 at 7 41 44 PM](https://user-images.githubusercontent.com/68735569/105362345-c9d7bd00-5c20-11eb-8af9-66e78de12892.png)

**Comment by kvyatkovskys** [comment]
Try to call `calendarView.reloadData()` when you change a type of view.

**Comment by learnasucan** [comment]
> Try to call `calendarView.reloadData()` when you change a type of view.

I have used this in switch calendar

**Comment by kvyatkovskys** [comment]
I'll check this, thx

**Comment by kvyatkovskys** [comment]
Could you record a video, pls?

**Comment by prachit1105** [comment]
https://user-images.githubusercontent.com/68735569/106285403-71c93800-626a-11eb-9e8b-4063134b1a57.mov

**Comment by kvyatkovskys** [comment]
But you use a `weekView` not a `monthView` 🤔
BTW, I couldn't reproduce on my device. Works fine

**Comment by learnasucan** [comment]
Yes its my mistake my segment index was pointing to week.You were right.Thanks a lot.

**Comment by prachit1105** [comment]
Yes , you were right my segment index was pointing to week view. Thanks for clarification.I am closing this issue.
