### ISSUE TITLE
data is still showing after deleting all events in database?

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#137]
**Describe the bug**
I have deleted all my events from my database.but all events are still I can view inside month view and dayView

**To Reproduce**
1. delete events in database
2. Go to calendar
3. Click on dayview or month view
4. In day view and monthview all events are visible

**Expected behavior**
events should not be visible

**Comment by kvyatkovskys** [comment]
Do you call method `calemdarView.reloadData()`? I couldn't reproduce this.
