### ISSUE TITLE
CalendarView not properly positioned and layed out

### ISSUE THREAD

**Issue by bouchtaoui-dev** [kvyatkovskys/KVKCalendar#138]
**Description**
I just simply created ViewController and than added CalendarView programmatically in viewDidLoad(). The result is a bit weird positioning of the calendar view on the simulator (not tested on real device yet).

**Screenshot of simulator**
<img width="393" alt="Screenshot 2021-01-22 at 18 27 28" src="https://user-images.githubusercontent.com/428598/105524764-64e39c00-5ce0-11eb-9535-a401dd6d6f01.png">

**Screenshot of code**
<img width="510" alt="Screenshot 2021-01-22 at 18 28 25" src="https://user-images.githubusercontent.com/428598/105524798-73ca4e80-5ce0-11eb-9c4d-8d8c0d6046c2.png">

What am I doing wrong and how I can fix this?

**Comment by kvyatkovskys** [comment]
Hello 🙂

Ohh... I need to change a default style for a Header view. 

For quick fix to to add the code ```
if UIDevice.current.userInterfaceIdiom == .phone {
            style.timeline.widthTime = 40
            style.timeline.currentLineHourWidth = 45
            style.timeline.offsetTimeX = 2
            style.timeline.offsetLineLeft = 2
            style.headerScroll.titleDateAligment = .center
            style.headerScroll.isAnimateTitleDate = true
            style.headerScroll.heightHeaderWeek = 70
            style.event.isEnableVisualSelect = false
            style.month.isHiddenTitle = true
            style.month.weekDayAligment = .center
        } else {
            style.timeline.widthEventViewer = 350
            style.headerScroll.fontNameDay = .systemFont(ofSize: 17)
        }```

**Comment by kvyatkovskys** [comment]
Example
`let calendar = CalendarView(frame: view.frame, date: selectDate, style: style) `
