### ISSUE TITLE
inconsitent data format

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#140]
**Describe the bug**
no proper dates

**To Reproduce**
1. Go to 'month view
2 See error

**Screenshots**
![Screenshot 2021-01-23 at 2 29 11 AM](https://user-images.githubusercontent.com/20422528/105546519-7e5a0780-5d23-11eb-9382-aff69374ae22.png)
![Screenshot 2021-01-23 at 2 29 24 AM](https://user-images.githubusercontent.com/20422528/105546525-8154f800-5d23-11eb-89e1-92291e8c68dd.png)
![Screenshot 2021-01-23 at 2 29 31 AM](https://user-images.githubusercontent.com/20422528/105546548-89ad3300-5d23-11eb-9d1b-0d432bcd8a53.png)
![Screenshot 2021-01-23 at 2 29 39 AM](https://user-images.githubusercontent.com/20422528/105546561-8ca82380-5d23-11eb-9dd0-d70c9d94c5dc.png)
![Screenshot 2021-01-23 at 2 29 45 AM](https://user-images.githubusercontent.com/20422528/105546576-8f0a7d80-5d23-11eb-9a67-5a9f68460cc5.png)
![Screenshot 2021-01-23 at 2 29 51 AM](https://user-images.githubusercontent.com/20422528/105546584-92056e00-5d23-11eb-8ae3-0132d45b9549.png)

**Comment by kvyatkovskys** [comment]
could not reproduce, works fine... need more details

**Comment by learnasucan** [comment]
Thanks
