### ISSUE TITLE
Request to keep single select date

### ISSUE THREAD

**Issue by UmeshCW** [kvyatkovskys/KVKCalendar#147]
Checked code in V 0.4.6, looks like 'didSelectDate' method deprecated and 'didSelectDates' is new one. But in this new method there is getting multiple date selection. I request to keep single selection for the dates as well.

**Comment by kvyatkovskys** [comment]
Multiple selection works only for the `monthView` and if the property is set to`Style.Month.selectionMode = .multiple`

**Comment by kvyatkovskys** [comment]
To get the date from an array just write `dates.first` 🙂
