### ISSUE TITLE
After scrolling of month view current month title is replaced by previous month

### ISSUE THREAD

**Issue by prachit1105** [kvyatkovskys/KVKCalendar#149]
**Describe the bug**
When I load month view current month January is showing but after scrolling vertically back December month was showing for both current and previous month.Next month February was correctly shown

**To Reproduce**
1. Go to Month view. current month is January 2021
2. scroll down to December month  2020.
3. Scroll up to January month then Your month title will be December 2020 not January 2021.
4. Again scroll up to February 2021 you will get proper date of February 2021

**Expected behavior**
After scrolling on each month you will get desire month not any other
**Screenshots**
https://user-images.githubusercontent.com/68735569/106352041-0fbe1080-6306-11eb-8237-e3200c04c1cf.mov

**Additional context**
It might be a minor issue while updating dateTitle on collection view scroll

**Comment by kvyatkovskys** [comment]
I guess, I already fixed this bug. Couldn't reproduce on the 0.4.6 version.
