### ISSUE TITLE
Scroll Header View

### ISSUE THREAD

**Issue by StarkSoftware** [kvyatkovskys/KVKCalendar#15]
Hi, I found this problem ....

If I select Sunday, then I scroll the week after some scrolls the dot on the date is not visible and the date is not selected.

This is the piece of code it looks like it comes into else

`guard let newMoveDate = cellDays.filter({ $0.day.date?.weekday == date.weekday }).first?.day.date, date != newMoveDate else { return }`

ScrollDayHeaderView.swift row 237

Thk's

**Comment by kvyatkovskys** [comment]
Hello!
Yeah, I can repeat this bug too. I'll try to fix it in next release 0.2.0. 
Thank you.

**Comment by kvyatkovskys** [comment]
Bug is fixed in release 0.2.1.

**Comment by kvyatkovskys** [comment]
Will be fixed in next release 0.2.1.
