### ISSUE TITLE
MonthView not properly positioned and layed out bug

### ISSUE THREAD

**Issue by dhotsky** [kvyatkovskys/KVKCalendar#151]
I just change default view from day to month, and i got result like this
i use Iphone 7

**Screenshoot iPhone 7**
![image](https://user-images.githubusercontent.com/40420988/106541962-7bd28b80-6535-11eb-9dc4-357e45f6b447.png)

**Screenshoot Code**
![image](https://user-images.githubusercontent.com/40420988/106542033-a3c1ef00-6535-11eb-92a5-26963eba8ade.png)

**Comment by kvyatkovskys** [comment]
What is your scroll direction for monthView? 🤔

**Comment by dhotsky** [comment]
i use horizontal direction

**Comment by kvyatkovskys** [comment]
The property `isPagingEnabled = true`?

**Comment by dhotsky** [comment]
Yes, isPagingEnabled is true

**Comment by kvyatkovskys** [comment]
Thx, I'll check 😉

**Comment by dhotsky** [comment]
Ok, i'll wait for it 
Thanks

**Comment by ronak-aecor** [comment]
I'm also facing the same issue.
The month view is showing appropriate data for only February month.

**Comment by kvyatkovskys** [comment]
couldn't reproduce.
Do you use an additional settings for the month view like a `style.month` or a custom size for cell
![Simulator Screen Shot - iPod touch (7th generation) - 2021-02-02 at 12 05 55](https://user-images.githubusercontent.com/8233076/106577106-04a9f100-654f-11eb-8d22-1f44c544d588.png)

**Comment by ronak-aecor** [comment]
HI,
I haven't made any additional changes, Still, I'm getting the issue.
![Simulator Screen Shot - iPhone X - 2021-02-02 at 14 45 53](https://user-images.githubusercontent.com/68314336/106578344-6ecd9080-6565-11eb-9ab8-8d5df3f99de8.png)

**Comment by kvyatkovskys** [comment]
Have you updated the pod to version 0.4.6?

**Comment by ronak-aecor** [comment]
No, It's 0.4.5

**Comment by kvyatkovskys** [comment]
Could you update, pls? And check again

**Comment by ronak-aecor** [comment]
Updated.
Still the same issue.

**Comment by kvyatkovskys** [comment]
interesting

**Comment by yugochen** [comment]
CocoaPods,I tried to update,but version is 0.4.5, thk

**Comment by ronak-aecor** [comment]
The view is not loading properly while integrating into any project.
When we download this project and run it at that time it is running properly. However, when we do any changes at that time this issue occurs.

**Comment by dmi3j** [comment]
For me bug disappeared once I set `isPagingEnabled = false`
