### ISSUE TITLE
 Weird look  when many day view events

### ISSUE THREAD

**Issue by prachit1105** [kvyatkovskys/KVKCalendar#153]
**Describe the bug**
Created many events on single day many view are seen at bottom

**To Reproduce**
1. Go to DayView

**Expected behavior**
only events are visible on day view otherwise it is clean look

**Screenshots**
![Screenshot 2021-02-04 at 12 59 44 AM](https://user-images.githubusercontent.com/68735569/106799114-ddedd680-6684-11eb-8a85-e815d524f6f5.png)
![Screenshot 2021-02-04 at 1 00 57 AM](https://user-images.githubusercontent.com/68735569/106799226-01b11c80-6685-11eb-913f-22fb909f2a0f.png)

**Additional context**
you can add property, style.dayView.CleanDayView = true

**Comment by kvyatkovskys** [comment]
You can hide stubs `style.timeline.isHiddenStubEvent = true`
