### ISSUE TITLE
sometimes didSelectDates() method gets automatically called

### ISSUE THREAD

**Issue by UmeshCW** [kvyatkovskys/KVKCalendar#154]
**Describe the bug**
didSelectDates() method gets called from other view controller, even no date selected on it's view controller

**Expected behavior**
didSelectDates() method should not get selected automatically

**Comment by kvyatkovskys** [comment]
🤔 I'll try to investigate the issue, thx.

**Comment by UmeshCW** [comment]
Hey, this issue looks like our issue, and not KVKCalendar issue. Thanks.
