### ISSUE TITLE
Recurring event not getting

### ISSUE THREAD

**Issue by UmeshCW** [kvyatkovskys/KVKCalendar#156]
**Describe the bug**
Set the recurring event for daily but it is not appearing on daily view

**Expected behavior**
Daily recurring event should appear on every date

**Comment by UmeshCW** [comment]
any updates on this?

**Comment by kvyatkovskys** [comment]
I'll check the issue later, I'm busy a bit with my work

**Comment by kvyatkovskys** [comment]
could not reproduce... works fine 
Could you provide a more details?
