### ISSUE TITLE
Setting offsetTimeY makes resizing events by gestures produce wrong time.

### ISSUE THREAD

**Issue by negovskiy** [kvyatkovskys/KVKCalendar#158]
**Resizing event produces incorrect dates**
Setting style.timeline.offsetTimeY makes resizing events by gestures produce wrong time.
didChangeEvent getting called with incorrect dates if offsetTimeY is not default

**To Reproduce**
1. Set style.timeline.offsetTimeY = 25
2. Press and hold on any event on day or week view
3. Try to change event duration and notice time you selected
4. Complete changing and see that event resized for not the selected time, but other

**Expected behavior**
Event should have same start & end time as it was while editing

**Additional context**
Also while resizing there supposed to be blue minute label, which is disappears when setting style.timeline.offsetTimeY = 25.

**Comment by kvyatkovskys** [comment]
Thanks for the issue. I'll check this
