### ISSUE TITLE
dayView event selection for long time behaves odd

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#160]
**Describe the bug**
After pressing long time on day view it gives white color ,event text becomes white

**To Reproduce**
1. Go to DayView
2. Click on 'Event' for long time
3. See error

**Expected behavior**
selectionBackground and textColor could be set by manually
style.event.eventSelectionTextColor = .black
style.event.eventSelectionBackgroundColor = .grey

**Screenshots**
https://user-images.githubusercontent.com/20422528/108112422-11385880-70bc-11eb-96d1-59b75c4cc7a4.mov

**Comment by kvyatkovskys** [comment]
you need to change the `color` and `backgroundColor` when you create an event

**Comment by learnasucan** [comment]
it should have different option to create and selection of event colors

**Comment by kvyatkovskys** [comment]
Feel free to create a PR 🙂 I'll review it.

**Comment by kvyatkovskys** [comment]
Anyway you can subscribe on the `func didSelectEvent` -> check the event -> change color -> reload array of events -> reload calendar

**Comment by kvyatkovskys** [comment]
In the next release, I plan to integrate a custom style for event like `event.style = EventStyle()` and you add an individual style for a different events
