### ISSUE TITLE
can't we have default height of event on timeline?

### ISSUE THREAD

**Issue by prachit1105** [kvyatkovskys/KVKCalendar#161]
**Is your feature request related to a problem? Please describe.**
I have added a 5-minute event in a timeline of the day view. But It acquires very small height as it very small event of time.

**Describe the solution you'd like**
you can start event height or width with a default value

**Describe alternatives you've considered**
style.eventStyle.height = 40
style.eventStyle.width = 40

**Additional context**
![Simulator Screen Shot - iPhone 8 Plus - 2021-02-17 at 17 32 29](https://user-images.githubusercontent.com/68735569/108209464-59a15600-7150-11eb-9b93-fb4068653131.png)

**Comment by kvyatkovskys** [comment]
hm, we can add a minimal size for events
