### ISSUE TITLE
Crash on importing events from system calendars

### ISSUE THREAD

**Issue by dmi3j** [kvyatkovskys/KVKCalendar#163]
**Describe the bug**
Once enable import from system calendars –> crash. 

**To Reproduce**
1. Enable import from system calendars by adding calendar names to systemCalendars
2. Launch app
3. Crash in TimelineView.swift at line 116

**Expected behavior**
System event imported

**Screenshots**
<img width="838" alt="crash" src="https://user-images.githubusercontent.com/120496/109056898-ba4d0780-76e9-11eb-8313-1221debc98dc.png">

**Additional context**
Installed via Cocoapods KVKCalendar (0.4.6)

**Comment by kvyatkovskys** [comment]
Hello 👋 

Thx for the bug. I'll check this
