### ISSUE TITLE
Can we control style properties  from outside controller?

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#166]
**Is your feature request related to a problem? Please describe.**
I was trying to modify TimeHourSystem.twentyFour property from outside setting controller using Notification center method.My variable is getting changed using notification center but style property is not changed anyway.After killing app timeline gets changed.Can you suggest me if I want to change any style property inside library, how can I changed it from outside controller?

**Describe the solution you'd like**
style.timeSystem = isTwentyFourHours ? TimeHourSystem.twentyFour : TimeHourSystem.twelve
Note:isTwentyFourHours is binded with notification center or any singlton varible inside app.After changing value of isTwentyFourHours style property should change.And it should not limited to timeSystem property .Every style property can be controlled using outside variable

**Describe alternatives you've considered**
There should be a  property which will communicate to outside controller internally handles calendar reloading and refreshing UI of it.

**Comment by kvyatkovskys** [comment]
Good point 👍🏼
I'm working on an ability to update the style of calendar dynamically. Perhaps, this's feature will be included in the next release `v. 0.4.8`
