### ISSUE TITLE
MothViewStyle Event loading behavior

### ISSUE THREAD

**Issue by MrCarter31** [kvyatkovskys/KVKCalendar#167]
When using the month view I noticed when scrolling to a new month the events don't load until a click as happened.  

For example when running the demo project, and selecting the month view initially all the events are loaded and shown as expected.  But when scrolling to January 2021, no events are shown on the month until you tap the screen.

Is there a way to fix this behavior?

This is shown when running the demo project, and scrolling to January 2021.  Events are not shown till screen is tapped.
<img width="1054" alt="Screen Shot 2021-03-04 at 9 23 22 AM" src="https://user-images.githubusercontent.com/50532982/110003536-515a2680-7ccb-11eb-8e27-f5fc0635d21b.png">

**Comment by kvyatkovskys** [comment]
Hello 👋

You need to enable the property `MonthStyle().isAutoSelectDateScrolling = true`

**Comment by kvyatkovskys** [comment]
FYI, I plan to rename the property in the next version
