### ISSUE TITLE
Monthview multi day events

### ISSUE THREAD

**Issue by MrCarter31** [kvyatkovskys/KVKCalendar#169]
I think the ability to create Muti day events will be very useful.  Currently there is not a single package on GitHub that recreates the apple calendar as closely as this package!  The next major implication could be adding the ability to display multi day events. 

Heres an example down below
![IMG_6E43CC4158D8-1](https://user-images.githubusercontent.com/50532982/110192230-940e2280-7de1-11eb-921b-0e9771932697.jpeg)

**Comment by kvyatkovskys** [comment]
You can create your own custom cell. Just subscribe on the method `dequeuCell` and return a custom cell for the month view 🙂
