### ISSUE TITLE
Events displayed only for current month

### ISSUE THREAD

**Issue by yevgeniyzhigadlov** [kvyatkovskys/KVKCalendar#171]
Calendar events by month are displayed only for current month. Events are not displayed in other months

**Comment by kvyatkovskys** [comment]
Hello 👋

You need to tap on date or enable the property `style.month.isAutoSelectDateScrolling`

**Comment by yevgeniyzhigadlov** [comment]
style.month.isAutoSelectDateScrolling not working. Events displayed only for current month

**Comment by yevgeniyzhigadlov** [comment]
How can I display events for other months?

**Comment by kvyatkovskys** [comment]
I'll check this case 🤔

**Comment by the-giologist** [comment]
I was actually about to start a discussion on this same topic. Even after setting 
`style.month.isAutoSelectDateScrolling = true`
When scrolling (some) month's events are not loaded, the date is selected, but they don't show up until the calendar is tapped. 
I'll try to provide more details later when I get a chance.

**Comment by kvyatkovskys** [comment]
I checked, it works fine for me. I plan to release a new version of library `0.4.8` and I renamed the property to `autoSelectionDateWhenScrolling`
