### ISSUE TITLE
When Phone is in 12-hours mode events become 24hours long

### ISSUE THREAD

**Issue by graldij** [kvyatkovskys/KVKCalendar#173]
Hello,
In the process of testing my app using the KVKCalendar, I noticed that whenever the iPhone has the 12-hours layout (e.g. 15.15 is 3.15 pm), the length of the events displayed is wrong: instead of the actual length they becomr 24-hours long (see screenshot). I tried to set `style.timeSystem = TimeHourSystem.twentyFour` but nothing has changed.
Is this a bug? Or are there some other style-settings useful to solve the problem?

Thanks!
![WhatsApp Image 2021-03-10 at 15 31 26](https://user-images.githubusercontent.com/56401352/110646452-31d56900-81b7-11eb-8e7c-bd11a66c22c6.jpeg)

**Comment by kvyatkovskys** [comment]
🤔 try to set `style.timeSystem = TimeHourSystem.twelve`

**Comment by graldij** [comment]
> 🤔 try to set `style.timeSystem = TimeHourSystem.twelve`

Nothing changes: correctly displayed for 24-hours system and with that strange behaviour for the 12-hours system

**Comment by graldij** [comment]
var i: Int=0
        for course in courses {

            let isoDateStart = course.startEvent
            let dateStartFormatter = ISO8601DateFormatter()

            let isoDateEnd = course.endEvent
            let dateEndFormatter = ISO8601DateFormatter()
            var event = Event(ID: "\(i)")

            event.start = dateStartFormatter.date(from: isoDateStart)!
            event.end = dateEndFormatter.date(from: isoDateEnd)!
            event.text = course.name

            events.append(event)

            i=i+1
        }


That's the way I am creating the events, fyi

**Comment by kvyatkovskys** [comment]
could you print `event.start & event.end`, pls? to check data 🤔

**Comment by graldij** [comment]
I found that the problem is actually the value returned by `dateStartFormatter.date(from: isoDateStart)!`, e.g. the time `2021-03-05 13:30:00 +0000` becomes `2021-03-05 1:30:00 PM +0000`. 🧐

**Comment by graldij** [comment]
For the following code 
```
var i: Int=0
for course in courses {

    let isoDateStart = course.startEvent
    let dateStartFormatter = ISO8601DateFormatter()

    let isoDateEnd = course.endEven
    let dateEndFormatter = ISO8601DateFormatter()
    var event = Event(ID: "\(i)")
            

    event.start = dateStartFormatter.date(from: isoDateStart)!
    event.end = dateEndFormatter.date(from: isoDateEnd)!
    event.text = course.name

    print(event.start)
    print(event.end)
            
    print(dateStartFormatter.date(from: isoDateStart)!)
    print(dateEndFormatter.date(from: isoDateEnd)!)
            
    events.append(event)

    i=i+1
}
```

I get these outputs for 12-hours system:
```
2021-03-05 11:30:00 AM +0000
2021-03-05 1:30:00 PM +0000
2021-03-05 11:30:00 AM +0000
2021-03-05 1:30:00 PM +0000
```
And these for the correct 24-hours system:
```
2021-03-05 11:30:00 +0000
2021-03-05 13:30:00 +0000
2021-03-05 11:30:00 +0000
2021-03-05 13:30:00 +0000
```

**Comment by kvyatkovskys** [comment]
I'll check this but I think the problem is related to `ISO8601DateFormatter()`

**Comment by graldij** [comment]
Okay, thanks! Please let me know if you find something!

**Comment by kvyatkovskys** [comment]
Could not reproduce, works fine for me 🤔

**Comment by graldij** [comment]
well, that's strange. Did you change the entire iPhone hour-system, right?

**Comment by fatenumber25** [comment]
I fixed it in TimelineView.swift as below and solved it.

Before
```
let timeLabelFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "HH:mm"
    return formatter
}()
```

After
```
let timeLabelFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "HH:mm"
    formatter.calendar = Calendar(identifier: .gregorian)
    formatter.locale = Locale(identifier: "en_US_POSIX")
    return formatter
}()
```

**Comment by kvyatkovskys** [comment]
Could you create a PR with your fix, pls?

**Comment by nefch** [comment]
Hi, what is the status? I see exactly the same behavior as described by graldij more than 3 years ago (!). Events in 24 hour mode are displayed correctly. In 12 hour mode, however, each event becomes a whole day! fatenumber25's "fix" does not work for me.

**Comment by kvyatkovskys** [comment]
> Hi, what is the status? I see exactly the same behavior as described by graldij more than 3 years ago (!). Events in 24 hour mode are displayed correctly. In 12 hour mode, however, each event becomes a whole day! fatenumber25's "fix" does not work for me.

Hi, I'll try to reproduce and fix the issue in the next release

**Comment by cendolinside123** [comment]
![IMG_1072](https://github.com/user-attachments/assets/f2e6b218-e7a8-431c-8bbf-e3ffdcf826b5)

https://github.com/user-attachments/assets/730482d3-39cb-4e88-933b-1e94c41fb642



this issue happend on demo app too @kvyatkovskys

**Comment by cendolinside123** [comment]
@kvyatkovskys If I debug, look like you have issue arround `kvkHour` (or maybe `kvkMinute` too) on Date extension. All value inside variable `timeLabels` on `TimelineEventLayoutContext` always give 0 on `hashTime` property

**Comment by cendolinside123** [comment]
<img width="705" alt="Screenshot 2024-10-09 at 11 43 41" src="https://github.com/user-attachments/assets/896778d5-1213-47e0-96b2-8b11ada88454">

root cause

**Comment by kvyatkovskys** [comment]
Thank you for your help. I'll try to fix this ASAP.

**Comment by kvyatkovskys** [comment]
@cendolinside123 can you check [this branch](https://github.com/kvyatkovskys/KVKCalendar/tree/feature/v_0.6.27) on your machine, pls?

**Comment by cendolinside123** [comment]
> @cendolinside123 can you check [this branch](https://github.com/kvyatkovskys/KVKCalendar/tree/feature/v_0.6.27) on your machine, pls?

Wait, I will try it soon

**Comment by nefch** [comment]
The fix works for me. Thanks!
