### ISSUE TITLE
MonthView with Events List

### ISSUE THREAD

**Issue by tudorpopa39** [kvyatkovskys/KVKCalendar#174]
Hi there, it would be nice if we could have a way to switch month view calendar into a combined form of month above and list bellow, like in the native Calendar.
If I can do this right now, maybe i didn't find it yet how to.
Please let me know what to thing about it. I really need this feature
![IMG_6922](https://user-images.githubusercontent.com/16446036/112449960-8d2d5c80-8d5c-11eb-9103-031b7b9156a7.PNG)

**Comment by kvyatkovskys** [comment]
Hmm, interesting. In the current version of library you need to create two object `KVKCalendar`. One for `monthView` and another one for `listView` 🤔

**Comment by kvyatkovskys** [comment]
I added a public attribute for the class `KVKCalendar.ListView`. Now you can create a separate view and add to your main view.  `ver. 0.5.0`
