### ISSUE TITLE
Change the y coordinate of Day view after adding multiple all day events

### ISSUE THREAD

**Issue by UmeshCW** [kvyatkovskys/KVKCalendar#175]
Is there any way to change y coordinate of Day view after adding multiple all day events?
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-30 at 16 43 44](https://user-images.githubusercontent.com/60099497/112981111-57cba900-9178-11eb-9bfb-bf0a476dc70a.png)

refer screenshot. After adding multiple all day events the start of the day 12.00 AM is getting hidden. Can we increase y coordinate of timeline after end of all day events?

**Comment by kvyatkovskys** [comment]
Good point👍🏻 I'll check the code and add corrections. Thx 🙂

**Comment by UmeshCW** [comment]
any updates on this?

**Comment by kvyatkovskys** [comment]
It will add in the next release. Sorry for a long answer 🙂

**Comment by UmeshCW** [comment]
Any updates on this?

**Comment by kvyatkovskys** [comment]
released `v 0.4.9` with fixes
