### ISSUE TITLE
Crash on loading WeekView

### ISSUE THREAD

**Issue by anbu-sekar** [kvyatkovskys/KVKCalendar#176]
**Crash on loading Weekview while week start and end range intercept another year**
 Crash occurs while choosing last week range of the year, For example :  week starts at -> 27-DEC-2021(Monday), week ends at -> 2-JAN-2022(Sunday). the main thing is in last week range of year in intercept with another year

**To Reproduce**
1. In order to load week view pass any date range that should be last week of the year
2. That week range should be intercept with another year 
3. For example :  week starts at -> 27-DEC-2021(Monday), week ends at -> 2-JAN-2022(Sunday)

**Expected behavior**
It Should load week with next intercepting year also

**Screenshots**
![Screenshot 2021-03-30 at 6 14 12 PM](https://user-images.githubusercontent.com/64524237/112994038-74231200-9187-11eb-928c-a6c7c1788917.png)

**Comment by kvyatkovskys** [comment]
Thx for the bug. I'll check it.
