### ISSUE TITLE
func willSelectDate(_ date: Date, type: CalendarType) not working properly

### ISSUE THREAD

**Issue by UmeshCW** [kvyatkovskys/KVKCalendar#177]
**Describe the bug**
1) When we scroll month, sometimes in willSelectDate() method we are getting two months dates. e.g.
I scrolled from May to June, then in console it is showing the dates of June and July even I haven't gone to July month. Also while scrolling back same thing happening like e.g. I am scrolling from November to October, then I am getting dates in console for two month i.e. October and September. 
2) Current month date not getting most of the time after scrolling next month to back current month. e.g. current month is April, and I scrolled back from May month to April, then willSelectDate() method doesn't gets called.
**To Reproduce**
1. Go to Month View
2. Scroll down Month views
3. Print date in willSelectDate() method
4. try to scroll months one by one, you will observe date is not printing properly i.e. date is not getting sometime

**Expected behavior**
After scrolling forward and backward months only the scrolled month date should get in willSelectDate() method

**Comment by kvyatkovskys** [comment]
I'll check, thx for the issue.
