### ISSUE TITLE
Is there any way to disable horizontal scroll Day view?

### ISSUE THREAD

**Issue by UmeshCW** [kvyatkovskys/KVKCalendar#178]
**Is your feature request related to a problem? Please describe.**
We want to disable horizontal scroll Day view, as we are scrolling vertically Day view.
Please add this option or suggest if there is way already present to achieve this.
![Simulator_SS](https://user-images.githubusercontent.com/60099497/114661083-0395fc80-9d14-11eb-9a20-511485017cc2.png)

**Comment by kvyatkovskys** [comment]
sure, I'll add an additional property, thx

**Comment by kvyatkovskys** [comment]
added an additional property `TimelineStyle.scrollDirections`
