### ISSUE TITLE
How to add border view to event at left side

### ISSUE THREAD

**Issue by UmeshCW** [kvyatkovskys/KVKCalendar#179]
**Is your feature request related to a problem? Please describe.**
Is there any way to add border view / UIView to event at left side on dayview so that timeline line don't get erased.
![Simulator Screen Shot - iPhone 8 Plus - 2021-04-19 at 11 21 11](https://user-images.githubusercontent.com/60099497/115188996-67009f80-a103-11eb-83da-5f1fcf3b7685.png)

**Comment by kvyatkovskys** [comment]
when you create events just set the property `event.color = Event.Color(item.color)`

**Comment by UmeshCW** [comment]
Worked, thanks!!
