### ISSUE TITLE
Unable to set vertical lines in week View

### ISSUE THREAD

**Issue by karunhappy** [kvyatkovskys/KVKCalendar#180]
Version: 'KVKCalendar', '0.3.4'
iOS 14

I have tried setting the vertical day divider to true, although it is true by default. I have tried with example code too, have tried setting all the styles same as example code, but vertical lines in WEEK view are not visible.
`lazy var style: Style = {`
`var style = Style()`
`// timeline style`
`style.timeline.widthTime = 40`
`// Week style`
`style.week.showVerticalDayDivider = true`
`return style`
`}()`

Am I missing something? Please guide.
Thank you!
![simulator_screenshot_BC50A8D6-76D7-41E5-B853-9BD3AD7FA8D0](https://user-images.githubusercontent.com/3519777/115541861-3bc1b000-a2bd-11eb-9922-f86f98eadc43.png)

**Comment by kvyatkovskys** [comment]
Oh man, you use a very old version🤔
Can you update to the latest version `v. 0.4.8`?

**Comment by karunhappy** [comment]
I have updated to the latest version `0.4.9`, still cannot see vertical lines in week view. UI still remains same as above image. Do I need to add anything more?

**Comment by kvyatkovskys** [comment]
Check this property `week.showVerticalDayDivider` when you create style 🤔

**Comment by karunhappy** [comment]
I have fixed it somehow, still don't understand what was missing. I copied all the properties from the sample(all I already had) and also added other properties, and everything comes out expected.
So closing this thread.
