### ISSUE TITLE
.showLineHourMode does not show as expected.

### ISSUE THREAD

**Issue by the-giologist** [kvyatkovskys/KVKCalendar#181]
iOS: 14.2
iPad 7th Gen
KVK version: 0.4.8

I'm sure i'm missing a new property or something but I haven't been able to get the red current time line to show on .week or .day modes on the latest 0.4.8.
Perhaps this is in the middle of being updated?

`style.timeline.showLineHourMode = .always` OR .today

This property shows on 0.4.7 but not on 0.4.8.
I have been testing it on the example project and within another project.

In the screenshot I can see that the red line that should be there, is temporarily hiding the timeline hour label.
Any help or tips would be appreciated, thanks!
![kvk](https://user-images.githubusercontent.com/75033054/115565478-072f0380-a27f-11eb-8f31-c8e9ef5eeda1.jpg)

**Comment by kvyatkovskys** [comment]
Thanks for this. Looks like a bug. I can reproduce this. I'll fix the bug.
