### ISSUE TITLE
In some cases week view shows horizontal line

### ISSUE THREAD

**Issue by anbu-sekar** [kvyatkovskys/KVKCalendar#183]
**In some cases week view shows horizontal line**
In some cases horizontal lines in week view while week intercept with another year which means now I am showing first week of the year(2021) and now I am swap for show previous week which in last week of the year(2020) during this swap week view lines changed horizontally

**To Reproduce**
1. load first week on any first week of the year (ex: 2021)
2. swipe the week view in order to show previous week which is year last week(2020)
3. Now you can see week view lines gets changed

**Screenshots**
![Simulator Screen Shot - iPhone 8 Plus - 2021-04-24 at 22 30 15](https://user-images.githubusercontent.com/64524237/115966888-41352980-a54d-11eb-9c75-6be16ba90063.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-04-24 at 22 30 19](https://user-images.githubusercontent.com/64524237/115966892-44301a00-a54d-11eb-900e-6a4c81e81f37.png)

**Comment by kvyatkovskys** [comment]
hmmm... investigating

**Comment by anbu-sekar** [comment]
@kvyatkovskys any update on this

**Comment by kvyatkovskys** [comment]
Works fine for me... can't reproduce.
