### ISSUE TITLE
After adding lots of all day events, they are covering full screen in Day view

### ISSUE THREAD

**Issue by UmeshCW** [kvyatkovskys/KVKCalendar#185]
**Is your feature request related to a problem? Please describe.**
When I try to add lots of all day events in day view, e.g. I added 40 all day events then they are occupying full screen, so we are not able to see the Timeline events.

**Describe the solution you'd like**
This issue can be fixed if we add table view with specific height (e.g. 140 points) and all the all-day events can be added into that tableview, so It won't occupy all screen

**Describe alternatives you've considered**
You can refer iPhone's or iPad's Calendar app, in which when we add multiple all day events they gets added into tableview/ collection view.

**Additional context**
![IMG_0149](https://user-images.githubusercontent.com/60099497/117151535-d00c3680-add6-11eb-85c7-fc0ddac1d8b7.png)
In this screenshot you can check, when I added lots of all day event then all day events occupying half of screen, and not able to see normal events, If I add 100s of all day event it will occupy all screen and will not able to see Day timeline at all

**Comment by kvyatkovskys** [comment]
sorry for the log answer... you mean, can't you scroll to top of the screen to see events at the beginnings?

**Comment by kvyatkovskys** [comment]
FYI, you can set this property `style.allDay.isPinned = false`

**Comment by UmeshCW** [comment]
Can we add All Day events in table view, and table view will have upto e.g.88points(you can keep anything you want) height. I have added the video recording of iPhone's Calendar's app, in which you can see I added 9 test events, so after adding more than 4 events the all day events gets into table view and I am able to scroll them. If you use table view for lots of All Day events, then those events won't occupy the whole screen, and if you add them in tableview it will look nice.

https://user-images.githubusercontent.com/60099497/118363631-ed998700-b5b2-11eb-8dbc-839fc185e2aa.mp4

**Comment by kvyatkovskys** [comment]
Good suggestion 👍🏻
