### ISSUE TITLE
Importing KVKCalendar in project breaks the build

### ISSUE THREAD

**Issue by lightman73** [kvyatkovskys/KVKCalendar#187]
**Describe the bug**
I have a number of custom UITableViewCells, each one defining a `static var identifier: String {...}` which always compiled with no problems or warnings. 

After adding KVKCalendar to the project, via CocoaPods, all those property definitions began throwing errors, in particular:
`Overriding non-@objc declarations from extensions is not supported` and 
`Overriding non-open static property outside of its defining module`

Both errors make no sense at all.

I tried removing the library, and all compiled properly again.

**Expected behavior**
Importing the library shouldn't break the build.

Using Xcode 12.5

Tried cleaning the build, removing the build folder, closing Xcode and reopening the project. Nothing seems to fix the problem.

Any help would be greatly appreciated.

**Comment by lightman73** [comment]
Ok, I think I identified the problem, it lies in `Calendar+Extension.swift`, where you have:
```
public extension UIView {
    static var identifier: String {
        return String(describing: self)
    }
}
```

Which obviously clashes with my local definitions. 

I think it might be a bit hazardous to define an extension to UIView defining a public static property with an obvious name like `identifier` which could easily be used in a project. 

Moreover, since properties and methods defined in an extension are not overridable, there is no easy solution for me other than changing all the `identifier` definition in subclasses of UIView...

**Comment by kvyatkovskys** [comment]
Thanks for the issue! Yeah, it seems that the problem is `identifier`. I'll change the property name in the next release

**Comment by lightman73** [comment]
Thanks for the quick answer ! 

I'd say you can close the issue, then 😊👍🏻
