### ISSUE TITLE
Wrong date of week for 1 Aug 2021

### ISSUE THREAD

**Issue by dmi3j** [kvyatkovskys/KVKCalendar#189]
**Describe the bug**
1 Aug 2021 in month view displayed as Monday, yet it should be Sunday.

**To Reproduce**
1. Open months view
2. Scroll to Aug 2021

**Expected behavior**
1 Aug 2021 should be Sunday 

**Screenshots**
![IMG_5EAD3E2CB037-1](https://user-images.githubusercontent.com/120496/118685369-ace87a80-b80b-11eb-99c2-aec9b1db4668.jpeg)

**Comment by kvyatkovskys** [comment]
Thanks for the issue 🙂
