### ISSUE TITLE
Calendar Not reloading properly with updated events/courses

### ISSUE THREAD

**Issue by KrGauravJha** [kvyatkovskys/KVKCalendar#190]
**Describe the bug**
The timeline view in "day" is not reloading the updated courses when scrolling through header scroll view to another week. I have implemented it in swiftUi.

**To Reproduce**
1. Go to 'Calendar Main view and tap on current week date in header view' day view.
2. Click on 'any data in current week and the time line is refreshed with updated events after api call on didselect dates.'
3. Scroll down to 'any other date from previous week from header scroll bar, the timeline will either will be blank or the same event is being displayed everyday'
4. Reloading of calendar is not working properly on scroll of "headerScroll" style default type is .day.

**Expected behaviour**
Calendar should update with the new events added after api call like happening in same week didselect.

apiCall(startDate: selectedDate ?? Date()) { (success, error) in
                if success!{
                    self.loadEvents() { (events) in
                        self.events = events
                        self.parent.calendar.reloadData()
                    }
                }else{
                    print("Error")
                }
            }

**Screenshots**
Events displaying in current week after api call

![IMG_1010](https://user-images.githubusercontent.com/74243119/118908306-cfc77b80-b93e-11eb-8a54-ae42dfa13a40.PNG)

Same Event being displayed on previous week also when there is different events from api.

![IMG_1011](https://user-images.githubusercontent.com/74243119/118908464-1ddc7f00-b93f-11eb-8e4e-bf2026fb6760.PNG)

**Additional context**

**Comment by krgauravjha78** [comment]
Update,

Now the duplicate event display is being resolved but the events in previous week is still not displayed.

Tried printing the frames and it's working fine but the event is not displayed in calendar.

**Comment by kvyatkovskys** [comment]
Thx for the issue. I'll check 🤔

**Comment by KrGauravJha** [comment]
Please find the details for looking into issue,

**let page = getEventView(style: style, event: event, frame: newFrame, date: date)
print("Page is \(page.frame)")**

**if !style.timeline.isHiddenStubEvent, let day = date?.day {
                print("Day is \(day)")
}**

I have placed the print statement to get the frame of newly added event in previous week and it's giving e correct frame

Page is (60.0, 810.0, 312.0, 473.271186440678)
Day is 12

but still event is not displayed there, maybe i need to reload day part from there or i am missing something.

**Comment by kvyatkovskys** [comment]
Do you subscribe on this method `func didSelectDates(_ dates: [Date], type: CalendarType, frame: CGRect?)` ?

**Comment by krgauravjha78** [comment]
No, I haven't subscribed the above method, I have subscribed to

func didSelectDate(_ date: Date?, type: CalendarType, frame: CGRect?) {
selectDate = date ?? Date()
Api call with selected date
loadEvents
self.view.calendar.reloadData()
}

**Comment by KrGauravJha** [comment]
Hi,

Yes it's been subscribed to the method

func didSelectDates(_ dates: [Date], type: CalendarType, frame: CGRect?) {
            let selectedDate = dates.first
            print("Selected Date is \(selectedDate!)")

            var style = Style()
            if Calendar.current.isDate(selectedDate!, inSameDayAs: Date()){
                style.timeline.backgroundColor = UIColor.yellow.withAlphaComponent(0.2)
                self.parent.calendar.updateStyle(style)
            }else{
                style.timeline.backgroundColor = UIColor.gray.withAlphaComponent(0.1)
                self.parent.calendar.updateStyle(style)
            }
            
            timeEntriesApiCall(startDate: selectedDate ?? Date()) { (success, error) in
                if success!{
                    self.parent.calendar.reloadData()
                }else{
                    print("Error")
                }
            }
 }

**Comment by KrGauravJha** [comment]
Update,

Thanks for timely response i have fixed the issue , the issue is due to updating style before reloading the calendar

  **if Calendar.current.isDate(selectedDate!, inSameDayAs: Date()){
         style.timeline.backgroundColor = UIColor.yellow.withAlphaComponent(0.2)
         self.parent.calendar.updateStyle(style)
 }else{
         style.timeline.backgroundColor = UIColor.gray.withAlphaComponent(0.1)
         self.parent.calendar.updateStyle(style)
  }**

Once i comment this part in **"didSelectDates(_ dates: [Date], type: CalendarType, frame: CGRect?)"** the working is as expected, you can close this issue
Thanks
