### ISSUE TITLE
Fatal error: Can't form Range with upperBound < lowerBound file Swift/aram64-apple-ios.swiftinterface

### ISSUE THREAD

**Issue by saifullahsajid** [kvyatkovskys/KVKCalendar#191]
**What's the issue**
We are using KVKCalender in our iOS application to display time slots (with starting and ending times). The number of time slots can vary from 1 to 8000~. Which leads to a huge performance issue when the number is higher. Apart from that this framework works fine but throws this error, one in fifty times. This issue occurs in `TimelineModel.swift` line 72. 

**To Reproduce**
Simple go to KVKCalender again and again.

**Screenshots**
![Screenshot 2021-05-27 at 10 37 01 PM](https://user-images.githubusercontent.com/18142681/119967644-039d4380-bfc6-11eb-87cc-54448b333aa9.png)

**Comment by kvyatkovskys** [comment]
hmm, thx for the issue... I'll add a workaround to fix the issue

**Comment by Saifullahsajid** [comment]
That would be great. Thank you very much.
