### ISSUE TITLE
Unable to set specific locale for the current time in the timeline of day, week and the date in the section header of the list

### ISSUE THREAD

**Issue by saifullahsajid** [kvyatkovskys/KVKCalendar#192]
**What's the issue?**
When I switch the language of the application to Arabic the calendar also converts to Arabic locale which is normal but I want to enforce the 'en' locale for the calendar even if the application language is not English by setting `style.locale = Locale(identifier: "en_AU")`. But it only affects the years and months and some areas of days, weeks and list. As mentioned in the title of the issue the current time of the timeline of days and weeks are not affected by setting the locale and also the section headers in the list.

**To Reproduce**
1. Change the language of the application.
2. Go to the calendar view.

**Screenshots**
![Simulator Screen Shot - iPhone 12 - 2021-05-31 at 10 36 31](https://user-images.githubusercontent.com/18142681/120146117-071b0f80-c1fe-11eb-88ca-8e4c7b61096f.png)
![Simulator Screen Shot - iPhone 12 - 2021-05-31 at 10 41 08](https://user-images.githubusercontent.com/18142681/120146126-0aae9680-c1fe-11eb-9e95-edbb636fd553.png)

**Comment by kvyatkovskys** [comment]
hmm, for me works fine 🤔... check your key `Localization native development region` in `Info.plist`

**Comment by kvyatkovskys** [comment]
but I have a little issue with headers for the `ListView`

**Comment by kvyatkovskys** [comment]
to change the title for `AllDayView` add new text to `AllDayStyle.titleText`

**Comment by saifullahsajid** [comment]
> to change the title for `AllDayView` add new text to `AllDayStyle.titleText`

This does not affect the `currentLineHour` value. How can I enforce the English locale on `currentLineHour` value?

**Comment by kvyatkovskys** [comment]
Hmmm 🤔

**Comment by kvyatkovskys** [comment]
released a new version `0.5.1`
