### ISSUE TITLE
Is it possible to shift from year to specific month by clicking on it and from month to a week or day?

### ISSUE THREAD

**Issue by saifullahsajid** [kvyatkovskys/KVKCalendar#194]
**The Problem**
Right now we are unable to interact with months inside year and weeks inside months and vice versa.

**Suggested Solution**
If we click on a certain month in a year, it should open that month in the monthly view. If we click on a specific day from the weekly/monthly view, it should open the day in detail today view.

**Comment by kvyatkovskys** [comment]
You need to change a calendar type `calendarView.set(type: type, date: selectDate)`
`calendarView.reloadData()` when you select date

**Comment by saifullahsajid** [comment]
> You need to change a calendar type `calendarView.set(type: type, date: selectDate) calendarView.reloadData()` when you select date

Thanks but why is `didSelectDates` called when the year tab is clicked in the segmented control for changing calendar type? I want to pull some condition inside `didSelectDates` as it is supposed to be called when a date is selected but it's also called when the year tab is clicked. In fact, it is not called on selecting any other tab than year.

**Comment by kvyatkovskys** [comment]
seems like a bug... I'll check it 🤔
