### ISSUE TITLE
disable scrolling on day view

### ISSUE THREAD

**Issue by prachit1105** [kvyatkovskys/KVKCalendar#195]
**Describe the bug**
I am not able to disable scrolling horizontally. I have customized the calendar and I changed the calendar day or month change by using button action. So I want to disable swipe to change day or month

**To Reproduce**
1. Go to the calendar
2. Click on 'day'
3. Scroll left or right to  change day or month
4. you can scroll horizontally that's an issue for me

**Expected behavior**
I want to disable scrolling of this screen by hand it should be done by my custom action buttons

**Comment by kvyatkovskys** [comment]
Hey!

You can control scroll directions 
`TimelineStyle.scrollDirections` 🙂

**Comment by prachit1105** [comment]
Thanks for the reply,

here I want to disable it.no scrolling by hand.

**Comment by kvyatkovskys** [comment]
Yeah, if you wanna disable only horizontal scrolling just set a legal direction `scrollDirections = [.vertical]`
