### ISSUE TITLE
can we add  different title name for each recurring event

### ISSUE THREAD

**Issue by prachit1105** [kvyatkovskys/KVKCalendar#196]
**Is your feature request related to a problem? Please describe.**
I want to add a different title name for each recurring event but now a single title goes to the event. We should have a provision to add differently description or title to recurring event

**Describe the solution you'd like**
suppose you have 10th June of a daily event and the event title is walk
then on 11 June, you want the title name to be like  Walk + Excercise for the same daily event 

**Describe alternatives you've considered**
You should provide a different collection for such daily or month events add after that with old event collection to display

**Comment by kvyatkovskys** [comment]
Hmmm, you can create a custom cell for the recurring events or to set a different title when you prepare events 🤔

**Comment by prachit1105** [comment]
yes. Now we are adding only one event but in a recurring state, for different days events may have different behavior. There should have a provision for this.

**Comment by kvyatkovskys** [comment]
I see no problems with using a custom event view for a recurring state for different days 🙂
