### ISSUE TITLE
can we disable timeline scroll ?

### ISSUE THREAD

**Issue by prachit1105** [kvyatkovskys/KVKCalendar#197]
**Is your feature request related to a problem? Please describe.**
I have manually added movement of day view. So I want to disable it like month view style,  style.month.isScrollEnabled = false

**Describe the solution you'd like**
style.timeline.isScrollEnabled = false

**Comment by kvyatkovskys** [comment]
Use please the property `style.timeline.scrollDirections`

**Comment by prachit1105** [comment]
style.timeline.scrollDirections = Set(minimumCapacity: TimelineStyle.ScrollDirectionType.vertical.rawValue)

This works! Thanks buddy
