### ISSUE TITLE
Red Circle of selected date getting cut off

### ISSUE THREAD

**Issue by niklasgrewe** [kvyatkovskys/KVKCalendar#202]
Hi, first thank you very much for this repo. I am using KVKCalendar with SwiftUI. I follow the instructions in the readme. It works, but the circle of the selected date getting cut off like this:

<img width="564" alt="Bildschirmfoto 2021-08-09 um 16 16 34" src="https://user-images.githubusercontent.com/61348836/128721325-cfc8cda1-ec0b-4fef-80e2-7a80d264521e.png">

i initiate the `CalendarView` like this:

```swift
private var calendar: CalendarView = {
        var style = Style()
        return CalendarView(frame: UIScreen.main.bounds, style: style)
    }()
```
How can i solve this UI Issue?

**Comment by kvyatkovskys** [comment]
Hello and thank you!

Just try to set ` style.headerScroll.heightHeaderWeek = 70`

**Comment by niklasgrewe** [comment]
thanks it works 👍
