### ISSUE TITLE
Disable the editing / creation of new events

### ISSUE THREAD

**Issue by AndreProc** [kvyatkovskys/KVKCalendar#203]
Hi, I like your calendar and I'm trying to add it in an application where I have to show a set of events + the system events. The user can click on an event but should not be able to create or edit an event. How can I disable the graphic effect of creation and modification?
In the first image I show that the long click allows the creation of a new event. (I want to disable that)
In the second image I show the modification of the event. (I want to disable that)
In the third image I want to change the red color of the currently selected month and I want to disable the days multiple selections. 
Thanks, AP 

KVKCalendar 0.5.1
![creation](https://user-images.githubusercontent.com/30795986/128718727-12d3db5e-b9d3-4120-a1e2-6560452de595.png) 
![editing](https://user-images.githubusercontent.com/30795986/128718724-72be8cfb-ceca-400b-8608-733064f65226.png)
![multiple_selection](https://user-images.githubusercontent.com/30795986/128718718-c4018e32-6003-4edf-a404-8ed06d3dbcef.png)

**Comment by kvyatkovskys** [comment]
Hello!

so, you need to follow the next steps:

- disable `isEnabledCreateNewEvent` -> (style.timeline)
- set up the necessary items `states = [.move, .resize]` -> (style.event)
- set the property `selectionMode = .single` -> (style.month)

**Comment by kvyatkovskys** [comment]
to change the color of current month 🤔 I need to add a minor fix... I'll add a new property in ver. 0.5.3
