### ISSUE TITLE
How can i display System Events using SwiftUI?

### ISSUE THREAD

**Issue by niklasgrewe** [kvyatkovskys/KVKCalendar#204]
Hi, at the moment, i am using the following code to use KVKCalendar in SwiftUI. It works, but how can i display System Events, coming from Eventkit? My code looks like this:

```swift
struct CalendarDisplayView: UIViewRepresentable {
    @Binding var events: [Event]
    var type: CalendarType
    typealias UIViewType = CalendarView
    
    private var calendar: CalendarView = {
        var style = Style()
        style.headerScroll.heightHeaderWeek = 70
        return CalendarView(frame: UIScreen.main.bounds, style: style)
    }()
    
    func makeUIView(context: UIViewRepresentableContext<CalendarDisplayView>) -> CalendarView {
        calendar.dataSource = context.coordinator
        calendar.delegate = context.coordinator
        calendar.set(type: type)
        calendar.reloadData()
        return calendar
    }
    
    func updateUIView(_ uiView: CalendarView, context: Context) {
        
    }
    
    func makeCoordinator() -> CalendarDisplayView.Coordinator {
        Coordinator(self)
    }
    
    public init(events: Binding<[Event]>, type: CalendarType) {
        self._events = events
        self.type = type
    }
    
    class Coordinator: NSObject, CalendarDataSource, CalendarDelegate {
        private let view: CalendarDisplayView
        
        var events: [Event] = [] {
            didSet {
                view.calendar.reloadData()
            }
        }
        
        init(_ view: CalendarDisplayView) {
            self.view = view
            super.init()
        }
        
        func eventsForCalendar(systemEvents: [EKEvent]) -> [Event] {
            return events
        }
    }
}
```
I am using the `CalendarDisplayView` in SwiftUI like this:

```swift
struct ContentView: View {
    @StateObject var eventKitWrapper = Shift.shared
    @State var events: [Event] = []
    
    var body: some View {
        NavigationView {
            CalendarDisplayView(events: $events, type: .day)
                .navigationBarTitle("Calendar", displayMode: .inline)
                .onAppear {
                    eventKitWrapper.fetchEventsForToday() { result in
                        switch result {
                        case let .success(events): print(events) // got events
                        case let .failure(error): print(error) // handle error
                        }
                    }
                }
        }
    }
}
```
To get the System Events, i am using an Eventkit wrapper called [Shift](https://github.com/vinhnx/Shift). It works, i get the events, but how can i display them in my `CalendarDisplayView`? What do i need to change or add to display the events in my calendar?

Note: sorry, actually I wanted to ask the question as it says in the readme, on stackoverflow, but unfortunately I am not able to create the tag KVKCalendar.

**Comment by kvyatkovskys** [comment]
Hi, just add title of calendars `style.systemCalendars = ["Calendar"]` and you get `systemEvents: [EKEvent]` in the function 
`func eventsForCalendar(systemEvents: [EKEvent]) -> [Event] {
            return events
  }`

**Comment by niklasgrewe** [comment]
@kvyatkovskys thanks for your quick answer. I added `style.systemCalendars = ["Calendar"]` and as you can see, i already implemented the `eventsForCalendar()` function. but still no system events are displayed:

```swift
func eventsForCalendar(systemEvents: [EKEvent]) -> [Event] {
   print("System Events: \(events)") // output: []
   return events
}
```
have I forgotten anything? 

do I need to extend the `eventsForCalendar()` function somehow? and what I don't quite understand... when do I have to pass events to the `CalendarDisplayView()`, when I can get the system events via the function  `eventsForCalendar()`?

**Comment by kvyatkovskys** [comment]
oh man 🙂

<img width="762" alt="Screenshot 2021-08-10 at 14 09 46" src="https://user-images.githubusercontent.com/8233076/128856788-460feb83-1a82-4d2f-88e0-6929196c8d24.png">

**Comment by kvyatkovskys** [comment]
also you can filter a system events if you need it

**Comment by niklasgrewe** [comment]
awesome, thank you it works now, sorry i am a beginner of Swift, so everthing is new to me 😄 one more question. In your readme i find this:

> To use a custom view for specific event or date you need to create a new view of class EventViewGeneral and return the view in function.

how can i do that with SwiftUI? Do i need to change something in the `eventsForCalendar()` function?

**Comment by niklasgrewe** [comment]
@kvyatkovskys can i set `style.systemCalendars = ["Calendar", "Calendar2"]` dynamically, because how should I know how many calendars and there title the user has?

**Comment by kvyatkovskys** [comment]
Hmm 🤔 
Try to add a new calendars and call function `calendar.updateStyle()`

**Comment by kvyatkovskys** [comment]
Perhaps, you need to call `calendar.reloadData()` after updating style
