### ISSUE TITLE
Problem with loading System Events

### ISSUE THREAD

**Issue by niklasgrewe** [kvyatkovskys/KVKCalendar#206]
Hi, i tested the sample App inside the example folder on my real device with my real calendar events. I loaded my four system calendars, specified in `style.systemCalendar = ["Cal1", "Cal2", "Cal3", "Cal4"]`

Everthing works as expected, but the app can no longer be operated smoothly. When I switch between day, week and month, it takes up to 5 seconds to load the view. I can also notice a delay when i switch between weeks. The most fluid i could switch between individual days.

Is there any way to optimize this? Can perhaps only a certain number of EKEvents be loaded and more are reloaded?

when I use Apple's own calendar, I don't have these delays, even though they are the same number of events. How do they do it so that the app can always be used smoothly?

**Comment by kvyatkovskys** [comment]
Hmm 🤔, interesting
Thx for the issue... I'll check the problem

**Comment by niklasgrewe** [comment]
thanks and i also noticed that the 7 days in the week view take a long time to update, when using system events:


https://user-images.githubusercontent.com/61348836/128924780-272dc163-105d-49b9-8850-0d9a8c2c590b.mov

**Comment by kvyatkovskys** [comment]
Hello! 

Could you check the branch `feature/v.0.5.3` on your Mac to test the issue, pls?
