### ISSUE TITLE
Week style with number of days customizable

### ISSUE THREAD

**Issue by fatenumber25** [kvyatkovskys/KVKCalendar#214]
Thank you for your great framework.

I have one request. Could you add new style as Week style but the number of days can be customizable please? I want to create Week view as Apple calendar.

**Comment by kvyatkovskys** [comment]
Hello and thank you!

Hmmm, I can add an additional method to use your a custom header view for Day/Week view

**Comment by fatenumber25** [comment]
Thank you for your reply.

On the device with a small screen such as the iPhone SE, even if the screen is landscape, the display for one week will be difficult to see, so I would like to display it every 4 or 5 days. So could you add it if possible?

**Comment by kvyatkovskys** [comment]
hmm, interesting 🤔
I'll figure out about this issue, thx.

**Comment by kvyatkovskys** [comment]
Anyway, I'll create an additional method to insert your a custom header view in Day/Week view.

**Comment by fatenumber25** [comment]
Thank you for your reply.  
I'm looking forward to new additions.

**Comment by kvyatkovskys** [comment]
ver. 0.6.5 has an additional property `Style().week.daysInOneWeek`... I guess, I can close this issue
