### ISSUE TITLE
When moving between weeks on week view events disappear. 

### ISSUE THREAD

**Issue by bitdelve** [kvyatkovskys/KVKCalendar#216]
I have a recurring event starting 1 year ago for each day of the week. When swiping on the week view either left or right, the events will disappear.

**Comment by kvyatkovskys** [comment]
When did your recurring event start? I’m asking because you need to include one flag to show a recurring event in the past.

**Comment by bitdelve** [comment]
I have it starting in the past. One date is 2019/11/15. What flag do I need to include?

**Comment by kvyatkovskys** [comment]
Your event will show starting with 2019/11/15. Oooops... my bad, I'll add a new property in `Style -> Event` like `showRecurringEventInPast`

**Comment by bitdelve** [comment]
Ok, however I have this issue even on non recurring events. I create an event for a couple days ago, and when I swipe to the date that should show it, it doesn't show.

**Comment by kvyatkovskys** [comment]
Interesting, but I can't reproduce using my test data.

**Comment by bitdelve** [comment]
SO what is happening to me maybe in better detail, is that when I load the calendar view with the events. It will show the events for the first set of dates (current day or week or month), but if I then swipe left or right to go to another set of dates it doesn't display them. I do get a list of events from the delegate method of didDisplayEvents, but nothing shows. Any ideas?

**Comment by bitdelve** [comment]
Basically it's only showing events for the current day, week, or month. I.E. Today is 2021-12-17 so I only see the event on the calendar for that day.

**Comment by kvyatkovskys** [comment]
Did you call `calendar.reloadData()` when you changed date?
