### ISSUE TITLE
Week view display issue

### ISSUE THREAD

**Issue by petrmihaela** [kvyatkovskys/KVKCalendar#220]
Appointments with close start time are displayed wrong in week view.

1. Add 1 appointment on 10 Jan 2021 at 11:08 am.
2. Add 1 appointment on 10 Jan 2021 at 11:15 am.
3. Go to week view.
4. Second appointment is displayed on 11 Jan column.

Note: I could reproduce it on iphone 8+. Everything is fine on iphone 12.
![Simulator Screen Shot - iPhone 8 Plus - 2022-01-10 at 10 26 35](https://user-images.githubusercontent.com/44923329/148737830-ce7bffd3-1d61-4f25-ae7b-3dfb07d37134.png)
![Simulator Screen Shot - iPhone 12 - 2022-01-10 at 10 27 06](https://user-images.githubusercontent.com/44923329/148737843-30250b29-b277-40dd-9514-da18a285cc55.png)

**Comment by kvyatkovskys** [comment]
Hi. 

Thanks for the issue. I'll check 😉

**Comment by kvyatkovskys** [comment]
couldn't reproduce on ver 0.6.5 🙂
