### ISSUE TITLE
Months date are repeating in last week and in first week

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#222]
**Describe the bug**
1. I have implemented custom day cell inside that months  date are repeating in last week and in first week Also Month tile is moving as per first day of month .
2. Also I want to place title of month  in left side of month calendar

**To Reproduce**
1. Go to '.Month'
2. Click on Month
3.. See error

**Expected behavior**
All week dates should not repeated
Month title in left or right side

**Screenshots**
![datesArerepeating](https://user-images.githubusercontent.com/20422528/153651275-59905d7e-585d-4b14-ba65-62a0e915b67e.jpeg)

**Comment by kvyatkovskys** [comment]
This is not a bug 🙂

1. Return an empty disabled cell for dates for an another month in section. 
2. You can use a custom header view for each section 

`public func dequeueHeader<T>(date: Date?, type: CalendarType, view: T, indexPath: IndexPath) -> KVKCalendarHeaderProtocol? where T : UIScrollView {} `

**Comment by learnasucan** [comment]
hi ,

Thanks for your reply. Custom header works perfectly.
But returning an empty cell for another  month in the section  is not
understood. Can you  explain?



*Thanks and Regards,*

*Prachit Patil*
*New Panvel*

**Comment by kvyatkovskys** [comment]
you need to check day type inside function where you create your own custom cell

```swift
case .day, .week, .month:
           guard dateParameter.type != .empty else { 
                // here return nil or create an empty cell
                // let emptyCell = UICollectionViewCell()
                // emptyCell.isUserInteractionEnabled = false
                // but if you return nil you have to disable `showDatesForOtherMonths`
                 return nil 
            }
            
            let cell = (view as? UICollectionView)?.kvkDequeueCell(indexPath: indexPath) { (cell: CustomDayCell) in
                cell.imageView.image = UIImage(named: "ic_stub")
            }
            return cell
```

**Comment by learnasucan** [comment]
Hi ,

Really appreciate for you update but implementing

           guard dateParameter.date?.day == Date().day &&
dateParameter.type != .empty else {
                // here return nil or create an empty cell
   // let emptyCell = UICollectionViewCell()                //
emptyCell.isUserInteractionEnabled = false                 return nil
            }

this code my custom code gets failed ,Removing of unnecessary dates in
calendar in month should be handled in library itself rather mixing
with custom implementation.





*Thanks and Regards,*

*Prachit Patil*
*New Panvel*

**Comment by kvyatkovskys** [comment]
can you share your crash?

**Comment by learnasucan** [comment]
Sure, here it is.

[image: IMG_B96F0D8CBB4F-1.jpeg]


//Dequeue Method implementation

    func dequeueCell<T>(dateParameter: DateParameter, type: CalendarType,
view: T, indexPath: IndexPath) -> KVKCalendarCellProtocol? where T:
UIScrollView {
        switch type {


        case .month, .day, .list, .year:
            guard dateParameter.date?.day == Date().day &&
dateParameter.type != .empty else {
                 // here return nil or create an empty cell
                 // let emptyCell = UICollectionViewCell()
                 // emptyCell.isUserInteractionEnabled = false
                  return nil
             }
            let currentMonth = dateParameter.date?.month

            let date = dateParameter.date


            print(Int(date!.convertToString("MM")) ?? 0)
            let cell = (view as?
UICollectionView)?.kvkDequeueCell(indexPath: indexPath, configure: { (cell:
CustomDayCell)  in
                let changeMonth = dateParameter.date?.month
//Int(date!.convertToString("MM")) ?? 0

                print(Int(date!.convertToString("MM")) ?? 0)

                if Date().convertToString("yyyy/MM/dd") ==
date!.convertToString("yyyy/MM/dd") {
                    cell.dayLabel.textColor = .white
                    cell.dayLabel.backgroundColor = UIColor(hexString:
"#F26F21")
                    cell.dayLabel.layer.cornerRadius = 12
                } else {
                    cell.dayLabel.textColor = UIColor(hexString: "#000000")
                    cell.dayLabel.backgroundColor = #colorLiteral(red: 1.0,
green: 1.0, blue: 1.0, alpha: 1.0)
                }

                if currentMonth == changeMonth {
                    cell.dayLabel.text = "\(date!.day)"
                } else {
                    cell.dayLabel.text = ""
                }


                for i in 0..<self.specialEventDates.count {
                    if self.specialEventDates[i].get(.day, .month,
.year).day! == date!.get(.day, .month, .year).day! &&
self.specialEventDates[i].get(.day, .month, .year).month! ==
date!.get(.day, .month, .year).month!{
                        cell.eventImage.image = UIImage(named: "ellipse")!
                    }
                }


                let selectedMonth = date!.get(.day, .month, .year).month!
                if self.yearlyEvents.count > 0 {
                    for i in 0..<self.yearlyEvents.count {

                        if date!.startOfDay >=
self.yearlyEvents[i].startDateMilliseconds.convertMilisecondsToDate().startOfDay
{

                            let yearlyDay =
self.yearlyEvents[i].startDateMilliseconds.convertMilisecondsToDate().startOfDay.get(.day,
.month, .year).day!
                            let yearlyMonth =
self.yearlyEvents[i].startDateMilliseconds.convertMilisecondsToDate().startOfMonth.get(.day,
.month, .year).month!

                            if selectedDay == yearlyDay && selectedMonth ==
yearlyMonth {
                                count = count + 1
                                if count > 0 {
                                    if count == 1 {
                                        cell.eventLabel.text = "\(count)
event"
                                    } else {
                                        cell.eventLabel.text = "\(count)
events"
                                    }
                                }
                            }
                        }
                    }
                }

                cell.contentView.borderWidth = 0.5
                cell.contentView.borderColor = .lightGray
                cell.contentView.cornerRadius = 2
       })

            return cell
        default:
            return nil
        }
    }


///Custom cell

class CustomDayCell: UICollectionViewCell{


    let dayLabel: UILabel = {
        let label = UILabel()
        label.textAlignment = .center
        label.font = UIFont(name: "SFProText-Medium", size: 14)
        label.clipsToBounds = true
        return label
    }()

    let eventImage: UIImageView = {
        let imageView = UIImageView()
        return imageView
    }()

    let eventLabel: UILabel = {
        let label = UILabel()
        label.textAlignment = .left
        label.font = UIFont(name: "SFProText-Medium", size: 10)
        label.textColor = UIColor.black.withAlphaComponent(0.6)


        return label
    }()

    override init(frame: CGRect) {
        super.init(frame: frame)

        contentView.addSubview(dayLabel)
        contentView.addSubview(eventImage)
        contentView.addSubview(eventLabel)

    }

    required init?(coder: NSCoder) {
           fatalError("Coder not implemented")
    }

    override func layoutSubviews() {
        super.layoutSubviews()

        dayLabel.frame = CGRect(x: (contentView.bounds.width / 2) - 12, y:
10, width: 24, height: 24)
        eventImage.frame = CGRect(x: (contentView.bounds.width / 2) - 3, y:
40, width: 6, height: 6)
        eventLabel.frame = CGRect(x: 10, y: contentView.bounds.height - 30,
width: self.bounds.width, height: 30)


    }
}






*Thanks and Regards,*

*Prachit Patil*
*New Panvel*

**Comment by kvyatkovskys** [comment]
I don't see crash logs 🤔
