### ISSUE TITLE
crash in  swiftui tabview 

### ISSUE THREAD

**Issue by mylovelycodes** [kvyatkovskys/KVKCalendar#224]
**Describe the bug**
app will crash in  swiftui tabview , need your help.

**To Reproduce**
`
TabView{
            NavigationView{
                CalendarContentView()
            }
            .tabItem {
                Text("Hello")
            }
        }`

**crash logs**

`
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'request for layout attributes for supplementary view UICollectionElementKindSectionHeader in section 13 when there are only 0 sections in the collection view'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001803e1188 __exceptionPreprocess + 236
	1   libobjc.A.dylib                     0x0000000180193384 objc_exception_throw + 56
	2   Foundation                          0x0000000180746648 _userInfoForFileAndLine + 0
	3   UIKitCore                           0x00000001844b88a4 -[UICollectionViewData layoutAttributesForSupplementaryElementOfKind:atIndexPath:] + 516
	4   UIKitCore                           0x000000018448660c -[UICollectionView layoutAttributesForSupplementaryElementOfKind:atIndexPath:] + 80
	5   OneOnOne                            0x00000001034c1bd4 $s11KVKCalendar9MonthViewC13scrollToIndex33_73D3F7115B466374126BB7344BEC2374LL_8animatedySi_SbtFyycfU_ + 564
	6   OneOnOne                            0x00000001033fd0dc $sIeg_IeyB_TR + 48
	7   libdispatch.dylib                   0x0000000105241694 _dispatch_client_callout + 16
	8   libdispatch.dylib                   0x00000001052443e0 _dispatch_continuation_pop + 560
	9   libdispatch.dylib                   0x000000010525926c _dispatch_source_invoke + 1384
	10  libdispatch.dylib                   0x0000000105250104 _dispatch_main_queue_callback_4CF + 836
	11  CoreFoundation                      0x000000018034fcd4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	12  CoreFoundation                      0x000000018034a244 __CFRunLoopRun + 2448
	13  CoreFoundation                      0x00000001803493a8 CFRunLoopRunSpecific + 572
	14  GraphicsServices                    0x000000018c03c5ec GSEventRunModal + 160
	15  UIKitCore                           0x0000000184d937ac -[UIApplication _run] + 992
	16  UIKitCore                           0x0000000184d982e8 UIApplicationMain + 112
	17  SwiftUI                             0x00000001b99bc7f4 $s7SwiftUI17KitRendererCommon33_ACC2C5639A7D76F611E170E831FCA491LLys5NeverOyXlXpFAESpySpys4Int8VGSgGXEfU_ + 160
	18  SwiftUI                             0x00000001b99bc750 $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 164
	19  SwiftUI                             0x00000001b94124f4 $s7SwiftUI3AppPAAE4mainyyFZ + 80
	20  OneOnOne                            0x0000000102dc3234 $s05OneOnA013LeadMyTeamAppV5$mainyyFZ + 40
	21  OneOnOne                            0x0000000102dc32e0 main + 12
	22  dyld                                0x0000000104f3dca0 start_sim + 20
	23  ???                                 0x00000001050590f4 0x0 + 4379218164
	24  ???                                 0x9a40000000000000 0x0 + 11114883880350384128
)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: 
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'request for layout attributes for supplementary view UICollectionElementKindSectionHeader in section 13 when there are only 0 sections in the collection view'
`

**Comment by ericboles** [comment]
@helloameon Did you ever find a solution to this crash in TabView?  I'm running into the same problem.
