### ISSUE TITLE
3 day view

### ISSUE THREAD

**Issue by mikeyyyzhao** [kvyatkovskys/KVKCalendar#227]
**Is your feature request related to a problem? Please describe.**
3 day view is quite popular for mobile, would be amazing to have a 3 day view 

**Describe the solution you'd like**
Similar to week view but with 3 days

**Comment by kvyatkovskys** [comment]
Hi!

Hmm, interesting 🤔. I'll figure it out and add to the next release. Thanks for the suggestion.

**Comment by mikeyyyzhao** [comment]
Thank you @kvyatkovskys ! This is an amazing library

**Comment by mikeyyyzhao** [comment]
@kvyatkovskys I see that the custom count days for week is merged, but I still see "work in progress" in the Style file. Is it possible to use three day view now?

**Comment by kvyatkovskys** [comment]
This feature is not ready, yet. I have some problems with week header... I plan to refactor (and fix some errors) week header in the next release
