### ISSUE TITLE
Multi-day all-day events are only displayed at the start and end of the event (days in the middle do not show the event)

### ISSUE THREAD

**Issue by mikeyyyzhao** [kvyatkovskys/KVKCalendar#228]
**Describe the bug**
For multi-day all day events (e.g. March 16 - March 20), the event only shows up on March 16 and March 20th). The event is missing in the middle of the days. 

**To Reproduce**
Create a test event from March 16 - March 20th

**Expected behavior**
![IMG_BAFE98A1B498-1](https://user-images.githubusercontent.com/4956032/158254124-c1a6e4e2-8f39-436c-9c3d-2fe99ef60ca7.jpeg)

**Comment by kvyatkovskys** [comment]
thank you for the issue!
