### ISSUE TITLE
Remove title date

### ISSUE THREAD

**Issue by mikeyyyzhao** [kvyatkovskys/KVKCalendar#229]
**Is your feature request related to a problem? Please describe.**
Expose a style for headerScroll to remove the UILabel for title date. I've tried isHidden and isHiddenSubview and neither remove the date title

**Describe the solution you'd like**
provide something like  "isHiddenTitleDate" to hide the UILabel (Wednesday, Jan 6, 2021) 

![Screen Shot 2022-03-14 at 5 46 02 PM](https://user-images.githubusercontent.com/4956032/158266674-46638211-e4aa-409d-a48f-8a9016d23f1d.png)

I've tried setting `isHiddenSubview` to true as well as changing `heightHeaderWeek` and `heightSubviewHeader` 's height but neither solution worked

**Comment by kvyatkovskys** [comment]
Nice catch! this's a bug
