### ISSUE TITLE
The column colors in week view are not uniform

### ISSUE THREAD

**Issue by mikeyyyzhao** [kvyatkovskys/KVKCalendar#231]
**Describe the bug**
It looks like the columns in week view are different colors?
![Screen Shot 2022-03-15 at 10 53 15 PM](https://user-images.githubusercontent.com/4956032/158507325-03280e04-fae2-4f6a-a34e-3c8bf5d6e893.png)

**To Reproduce**
Open any week view (screenshot is from example project) and the column colors are slightly different.

**Expected behavior**
Once you set the column color (with separatorLineColor), all the column colors should be the same. I've tried changing `shadowColumnColor` (not sure what this does to be honest) but doesn't look like it changed anything? Apologies in advance if this is a dumb question

**Comment by kvyatkovskys** [comment]
This issue seems to occur on simulator only🤔
I don't have problems on real device.
![image](https://user-images.githubusercontent.com/8233076/158526825-1eb3cc47-965d-40a3-ab5b-481493890251.png)

**Comment by mikeyyyzhao** [comment]
Weird, I'm seeing it on my real device as well (iPhone 13 pro max). I haven't adjusted any of the other styles for timeline
![IMG_FEBD2BFA26B4-1](https://user-images.githubusercontent.com/4956032/158620799-9d664213-d25a-4758-8583-4774b748a8dc.jpeg)

**Comment by kvyatkovskys** [comment]
Hm, interesting 🤔

**Comment by mikeyyyzhao** [comment]
Is there anything that I can send over to help you debug this issue?

**Comment by kvyatkovskys** [comment]
I'll try to check on simulators 🧐
