### ISSUE TITLE
All day events are not getting passed to willDisplayEventView

### ISSUE THREAD

**Issue by mikeyyyzhao** [kvyatkovskys/KVKCalendar#232]
**Describe the bug**
events denoted by isAllDay are not getting to `willDisplayEventView` and as a result, we can't customize all day events like we can non all day events.

**To Reproduce**
Using the example project, add conditional print statement inside `willDisplayEventView` to check for if any all day statements are getting passed in and see that none are. 

**Expected behavior**
All events (all day and non all day events) are getting based to `willDisplayEventView`

**Screenshots**

**Additional context**

**Comment by kvyatkovskys** [comment]
Thanks for the issue. I have  not yet implemented functionality as you described.

**Comment by kvyatkovskys** [comment]
added a new function for `CalendarDataSource`

`func dequeueAllDayViewEvent(_ event: Event, date: Date, frame: CGRect) -> UIView?`
