### ISSUE TITLE
Custom date formatter of Header View at Month style

### ISSUE THREAD

**Issue by fattiger00** [kvyatkovskys/KVKCalendar#233]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to custom dateformatter of Headerview in Month style. like:

![featureRequired](https://user-images.githubusercontent.com/38494401/159113032-0705234b-c3cb-4017-a24e-da45050805cf.png)

I want just set a property to modify the format.

**Describe alternatives you've considered**
After I read the source code, I found header views text format is driven by MonthStyle.shortInDaiMonthFormmatter. 

I tried to modify this property, but it's get only. 
![screenShot2022-03-19 16 06 27](https://user-images.githubusercontent.com/38494401/159113252-8ec2ed0a-ac5b-4bf1-a811-dbc66d1de871.png)

I also try to init a MonthStyle but :
![screenShot2022-03-19 16 08 00](https://user-images.githubusercontent.com/38494401/159113337-91b8e777-1196-4d61-81da-3b515e39df02.png)

MonthStyle is a struct, I can't Inheritance it.

**Additional context**
Your framework looks great, Can I contribute to this repo.? and For engagement timely, Could you share the architecture of this repo?

**Comment by kvyatkovskys** [comment]
Hello and thank you!
You need to use `style.month.weekdayFormatter` to customize days in week or you can use `func willDisplayHeaderSubview(date: _, frame: _, type:  _)` in your controller to display an another view. 
Yep, you can contribute if you want. (no storyboards, separate UI and data, POP)

**Comment by fattiger00** [comment]
Thanks, it works for me.
