### ISSUE TITLE
Crash on reloading the calenderview 

### ISSUE THREAD

**Issue by virkrishan** [kvyatkovskys/KVKCalendar#237]
Description

When a user creates a appointment on calender with same start and end date 
example : 
 start date -- > 23 march 2022 time 2:30 pm 
end date  -- > 23 march 2022 time 2:30 pm 

so in this case when you try to reload the calenderview it crashes . 

so please check this .

**Comment by kvyatkovskys** [comment]
Thanks for the issue. I'll check

**Comment by mikeyyyzhao** [comment]
Not sure if this is related issue, but I've found that sometimes on reloading calendarView, I'm getting a `Thread 1: "Invalid parameter not satisfying: [views count] == 3"` error on crash

**Comment by sabarics** [comment]
**Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [views count] == 3'**
This is happening on scroll in day/week view
