### ISSUE TITLE
darn n drop external event

### ISSUE THREAD

**Issue by Pamposgsk** [kvyatkovskys/KVKCalendar#238]
Hi,
Is there a possibility to create new events by drag n drop from a table next to the calendar?
thanks
pampos

**Comment by kvyatkovskys** [comment]
Hello!

Can you provide more details? I don't understand 🤔

**Comment by az-oolloow** [comment]
@kvyatkovskys this is a common use case e.g. for iPad - imagine user can drop items from a separate UITableView onto the calendar.

So you have say a list of activities to do - call mum, walk the dog etc. and you can drop them from this list to a spot on the calendar

**Comment by kvyatkovskys** [comment]
I guess, you can implement this functionality in your project
