### ISSUE TITLE
Month event is not getting loaded until select the month date

### ISSUE THREAD

**Issue by sabarics** [kvyatkovskys/KVKCalendar#241]
Month event is not getting loaded until select the month date. By default selected date, month events are displayed whereas when I scroll to next or previous month, events are not showing in Month.

added `style.month.autoSelectionDateWhenScrolling = true`

**Expected behavior**
When I scroll, events should be displayed every month 

![IMG_0042](https://user-images.githubusercontent.com/15062050/160773006-f771fece-db81-467e-9109-f59d76c7887d.PNG)|
![IMG_0043](https://user-images.githubusercontent.com/15062050/160773036-8633f9fb-076f-4c89-b10d-97b7c041bdad.PNG)
![IMG_0044](https://user-images.githubusercontent.com/15062050/160773047-a21fa16a-c77c-4195-89b1-5b994f1bd5b3.PNG)

https://user-images.githubusercontent.com/15062050/160773616-07421f4e-a33b-40b6-9f40-d3e7d9de7448.MP4

Here April 2022 month events are not getting displayed in the month view, after selecting any date on April month events is displayed.

**Comment by kvyatkovskys** [comment]
Hello!
hmm 🤔, interesting... I'll check, thanks for the issue.

**Comment by sabarics** [comment]
Hiiii
Any update @kvyatkovskys ?

**Comment by kvyatkovskys** [comment]
Not yet. Will check on this weekend

**Comment by sabarics** [comment]
Thank you

**Comment by kvyatkovskys** [comment]
you need to subscribe on this function 
`
func willSelectDate(_ date: Date, type: CalendarType) {
     print(date, type)
     calendarView.reloadData()
}
`

**Comment by sabarics** [comment]
Working @kvyatkovskys :+1:. Thanks for your time

**Comment by BhavinBhadani** [comment]
Hi @sabarics @kvyatkovskys  How events displayed in stripes? How to display vertical and horizontal both separator lines?

**Comment by sabari-zuper** [comment]
@BhavinBhadani Can you give more info?

**Comment by BhavinBhadani** [comment]
Hi @sabari-zuper I want to make same view like you did in month view that having events listed out like you did instead of dots. I think we need custom cell here. Is that correct?

**Comment by sabari-zuper** [comment]
yes.

**Comment by BhavinBhadani** [comment]
Thanks @sabari-zuper I am trying the same thing. Have you used anything like collection view in custom cell to handle events or some labels only?

**Comment by sabari-zuper** [comment]
No, I am not using any custom cell here. I am using the default one here.

**Comment by BhavinBhadani** [comment]
So, How you are able to get that stripes in green color with label because I only gets dots there

**Comment by sabari-zuper** [comment]
That is all-day event, Please refer example project.

**Comment by BhavinBhadani** [comment]
Yes, I am talking about all day event only that gives me dots and developed same as example project.

**Comment by sabari-zuper** [comment]
Can you share the screenshot of the example project?

**Comment by sabari-zuper** [comment]
This is how it looks on my iPad simulator. Please refer to the Month View in source code 
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-12-06 at 14 19 10](https://user-images.githubusercontent.com/106553101/205863990-79a1cc9e-589c-4ede-9efa-470b8c1fd65d.png)

**Comment by BhavinBhadani** [comment]
I think because it's iPad, it's showing like this. Thanks for your help @sabari-zuper

**Comment by sabari-zuper** [comment]
Thanks. If you want to same for iPhone, please do fork and changes as you want.

**Comment by dhavalSA** [comment]
> you need to subscribe on this function `func willSelectDate(_ date: Date, type: CalendarType) { print(date, type) calendarView.reloadData() }`

@kvyatkovskys this solution works only when we have style.month.autoSelectionDateWhenScrolling = true, in my case, I am using style.month.autoSelectionDateWhenScrolling = false to have the same user experience as Apple's default calendar, when we set style.month.autoSelectionDateWhenScrolling = false willSelectDate is not getting called then how can I show events without selecting any date
