### ISSUE TITLE
Swipe back a few days and then jump to today, red line is jumbo'ed on left hand side

### ISSUE THREAD

**Issue by mikeyyyzhao** [kvyatkovskys/KVKCalendar#242]
**Describe the bug**
the current time line
![Screen Shot 2022-03-31 at 9 32 33 AM](https://user-images.githubusercontent.com/4956032/161066871-25dab8f9-c886-448e-8a7a-71ceca149cd7.png)
 is jumbo'ed together in the time gutter

**To Reproduce**
In the example project, If you swipe left a few times and then press "today".

**Comment by kvyatkovskys** [comment]
Can you check the issue on last version 0.5.9? Works fine for me

**Comment by mikeyyyzhao** [comment]
Looks like it's working fine on the last version (0.5.9) but only broken when using the latest version of master

**Comment by kvyatkovskys** [comment]
Hmm, I'll check 😉
