### ISSUE TITLE
Custom Calendar implementation or show all days in calendar view?

### ISSUE THREAD

**Issue by sabarics** [kvyatkovskys/KVKCalendar#243]
Is there any way to show all days in day and week view?
Like this?
<img width="322" alt="Screenshot 2022-04-04 at 18 18 08" src="https://user-images.githubusercontent.com/15062050/161546995-7836d85d-5944-4e8f-b2bb-56c01682dc0a.png">

**Comment by kvyatkovskys** [comment]
You can create a new `calendarView` with mode = `.month`, for example.

**Comment by sabarics** [comment]
Thanks for you comment 🙏🏻. Is there any example to add new calendar to the existing calendar?

**Comment by kvyatkovskys** [comment]
No. You need to add two separate calendarView classes. My suggestion, create one class with Day/week `CalendarDayWeekView` and another one with month `CalendarMonthView`. And add these views to view in parent class `CalendarViewController`.
