### ISSUE TITLE
Panning/Moving Events

### ISSUE THREAD

**Issue by Mehul18292** [kvyatkovskys/KVKCalendar#25]
I wanted to move events from one time to other. Is there any way to do so in this library. I have checked your library, but i dont get any proper way. Can you please give me if there is any proper way for the same.

**Comment by kvyatkovskys** [comment]
Hi :)
Library hasn't possibly to move events in the current release. But I'll add the feature to next releases.

**Comment by kvyatkovskys** [comment]
Added a property to style `timeline.isEnableMoveEvent` to v.0.2.6
