### ISSUE TITLE
On updating style in KVKCalendar, Custom cell in dequeueCell not called. it reverses itself to default

### ISSUE THREAD

**Issue by ErSahil56** [kvyatkovskys/KVKCalendar#251]
if we update style like below

calendarView.style.timeSystem = calendarView.style.timeSystem == .twentyFour ? .twelve : .twentyFour
        if calendarView.style.headerScroll.heightHeaderWeek == 0 {
            calendarView.style.headerScroll.heightHeaderWeek = 60
        } else {
            calendarView.style.headerScroll.heightHeaderWeek = 0
        }
        calendarView.updateStyle(calendarView.style)
        calendarView.reloadData()

Custom cell code in func dequeueCell(dateParameter: DateParameter, type: CalendarType, view: T, indexPath: IndexPath) -> KVKCalendarCellProtocol? where T: UIScrollView { reverts and cell reverts back as default, even on scrolling, it never gets called and i was not able to find any fixes for it in library.

func dequeueCell<T>(dateParameter: DateParameter, type: CalendarType, view: T, indexPath: IndexPath) -> KVKCalendarCellProtocol? where T: UIScrollView {
        switch type {
        case .year where dateParameter.date?.month == Date().month:
            let cell = (view as? UICollectionView)?.kvkDequeueCell(indexPath: indexPath) { (cell: CustomDayCell) in
                cell.imageView.image = UIImage(named: "ic_stub")
            }
            return cell
        case .day, .week, .month:
            guard dateParameter.date?.day == Date().day && dateParameter.type != .empty else { return nil }
            
            let cell = (view as? UICollectionView)?.kvkDequeueCell(indexPath: indexPath) { (cell: CustomDayCell) in
                cell.imageView.image = UIImage(named: "ic_stub")
            }
            return cell
        case .list:
            guard dateParameter.date?.day == 14 else { return nil }
            
            let cell = (view as? UITableView)?.kvkDequeueCell { (cell) in
                cell.backgroundColor = .systemRed
            }
            return cell
        default:
            return nil
        }
    }

**Comment by kvyatkovskys** [comment]
Looks like an issue for Day/Week view 🤔 try to fix on this week.

**Comment by kvyatkovskys** [comment]
@ErSahil56 fixed the issue (v. 0.6.3)

**Comment by ErSahil56** [comment]
> @ErSahil56 fixed the issue (v. 0.6.3)

Thank you
