### ISSUE TITLE
Any way to allow/fix the Month label in Month calendar type to extend

### ISSUE THREAD

**Issue by rollyceballos** [kvyatkovskys/KVKCalendar#255]
**Describe the bug**
The `shortInDayMonthFormatter` text label is restricted by the size of the date frame when it's on the right most of the view.

I have allowed custom `shortInDayMonthFormatter` in the PR but realized it didn't handle layout restrictions like in the screenshot below.  Hope this can be fixed in 0.6.4

**To Reproduce**
1. In a month calendar type scroll to a month with day 1 (e.g. May 1, 2022) is the only date in a row (see screenshot below)
2. if `shortInDayMonthFormatter` is set to display longer than 3 characters - e.g. 'MMM yyyy' the text label is cut off with `...`3. 

**Expected behavior**
Labels should adjust accordingly to layout constraints - there is much space on the left

**Screenshots**
![Simulator Screen Shot - iPhone 12 mini - 2022-04-27 at 13 41 54](https://user-images.githubusercontent.com/20467695/165449692-3a01f8a7-0e92-4bb2-8395-c6ce4c161f3f.png)

**Comment by kvyatkovskys** [comment]
thx for the issue. To be fixed in the next release ver. 0.6.4
