### ISSUE TITLE
All-day event is not showing properly.

### ISSUE THREAD

**Issue by sabarics** [kvyatkovskys/KVKCalendar#257]
all-day event is not showing properly.

Event Data:
`{
    "data": [
        {
            "all_day": 1,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "start": "2022-04-26T09:00:00+03:00",
            "id": "1",
            "end": "2022-05-31T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 1",
            "files": []
        }
    ]
}
`

Here the start date is "**26/04/2022**" and the end date is "**31/05/2022**".  For the April month it shows properly for the date **26,27,28,29,30**, but in the may month it shows only for 31. 

**Expected Behaviour**
It should be shown for all the dates in may month

**Reference**
<img src="https://user-images.githubusercontent.com/15062050/167105449-e7787d4e-f7a2-4b97-9066-de9e9c445c2b.png" data-canonical-src="https://user-images.githubusercontent.com/15062050/167105449-e7787d4e-f7a2-4b97-9066-de9e9c445c2b.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/15062050/167105503-3a15939d-3620-4173-8f15-f0a874e3e165.png" data-canonical-src="https://user-images.githubusercontent.com/15062050/167105503-3a15939d-3620-4173-8f15-f0a874e3e165.png" width="200" height="400" />

**Comment by sabarics** [comment]
In Day, Week view is also the same, showing only for April month.

**Reference**
<img src="https://user-images.githubusercontent.com/15062050/167107029-36ed5afe-b6e8-47df-80eb-008649f79852.png" data-canonical-src="https://user-images.githubusercontent.com/15062050/167107029-36ed5afe-b6e8-47df-80eb-008649f79852.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/15062050/167107092-bd92a4a5-2f28-4644-beb3-6cb39b23df5f.png" data-canonical-src="https://user-images.githubusercontent.com/15062050/167107092-bd92a4a5-2f28-4644-beb3-6cb39b23df5f.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/15062050/167107134-50cd62e4-cb39-46e1-ac70-4e8919064da1.png" data-canonical-src="https://user-images.githubusercontent.com/15062050/167107134-50cd62e4-cb39-46e1-ac70-4e8919064da1.png" width="200" height="400" />

**Comment by kvyatkovskys** [comment]
Thx for the issue! I'll check the problem on the next week 🙂

**Comment by sabarics** [comment]
Any update?

**Comment by kvyatkovskys** [comment]
to be fixed in the next version 0.6.5

**Comment by sabarics** [comment]
@kvyatkovskys When can I expect version 0.6.5 ?

**Comment by kvyatkovskys** [comment]
> @kvyatkovskys When can I expect version 0.6.5 ?

Today or tomorrow... testing the new version

**Comment by sabarics** [comment]
@kvyatkovskys Thanks for the fix
