### ISSUE TITLE
How can show all day events in List?

### ISSUE THREAD

**Issue by sabarics** [kvyatkovskys/KVKCalendar#261]
Is there any way to show all day events in List?
 For Example -  If I have event for one week 16th may - 22nd May, I want to show events in all days(16-22).

**Comment by sabarics** [comment]
@kvyatkovskys any update?

**Comment by kvyatkovskys** [comment]
Perhaps I'll include a fix in the next release (ver. 0.6.6 or 0.6.7)

**Comment by rollyceballos** [comment]
Ditto on this same issue. Not just in list view but mine doesn't show up in the month view, but shows fine in the week and day view.  But do let me know if I should create an issue to track my own issue.

Mine is not showing multi-day all-day events in days in-between - e.g. Jan 10-17, only shows up on Jan 10, and Jan 17 on month and list view.

**Comment by sabarics** [comment]
@rollyceballos refer this #257

**Comment by sabarics** [comment]
@kvyatkovskys Thanks for the update

**Comment by rollyceballos** [comment]
> @rollyceballos refer this #257

yes, I updated to `0.6.5` but the issue of it not showing in dates between is still there for month view, and also list view. maybe I'll create a new issue tracker for the month view.

**Comment by rollyceballos** [comment]
Sorry scratch that. yeah I only have an issue with the List view not showing all-day events. so I'll just add in my vote here for a fix :)

**Comment by sabarics** [comment]
@kvyatkovskys When can I expect ver. 0.6.6?

**Comment by kvyatkovskys** [comment]
Perhaps this weekend

**Comment by sabarics** [comment]
any update ?

**Comment by kvyatkovskys** [comment]
Sorry very busy🙂 I'll include a fix for the issue to the next release 0.6.7

**Comment by sabarics** [comment]
@kvyatkovskys Thanks 🙂

**Comment by sabarics** [comment]
@kvyatkovskys Any update 🙂 ?
