### ISSUE TITLE
How to show event list in week view without time ?

### ISSUE THREAD

**Issue by JayamuruganG** [kvyatkovskys/KVKCalendar#263]
![screenshot](https://user-images.githubusercontent.com/63097352/169952057-1737db74-13d9-4ef7-bcdf-6c26edeecbc3.png)
i shared sample ui for your reference ?

**Comment by JayamuruganG** [comment]
@kvyatkovskys Is there any way to show events in vertical order(one by one)? Here I don’t want time, just show events on the respective date in vertical stacked order.In all day you are showing event in vertical order i want the same for events.
<img width="156" alt="Screenshot 2022-05-24 at 17 01 32" src="https://user-images.githubusercontent.com/63097352/170026128-c303325a-abd2-4bc9-b469-562594392cbd.png">

**Comment by JayamuruganG** [comment]
<img width="156" alt="Screenshot 2022-05-24 at 17 01 32" src="https://user-images.githubusercontent.com/63097352/170025985-a79b4909-629b-4ddd-b92a-7223c72ef646.png">

**Comment by kvyatkovskys** [comment]
Nope 🤔
This's a new functionality that may be included in the next release

**Comment by JayamuruganG** [comment]
Is there any workaround solution for time being?

**Comment by kvyatkovskys** [comment]
No 😕. It looks uncomplicated and I guess, I can include it in the ver. 0.6.6

**Comment by JayamuruganG** [comment]
thanks for update.Im waiting for ver 0.6.6😊

**Comment by kvyatkovskys** [comment]
@JayamuruganG Hello!
Testing a brand new mode (.list) for week view 🙂.
To enable the new mode you must make settings as shown below:
- style.week.viewMode = .list
- style.event.defaultHeight = 50 (for example)

![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-05-27 at 01 43 35](https://user-images.githubusercontent.com/8233076/170591422-f03de8bb-31d7-494f-b940-0184fe5a22d3.png)

**Comment by JayamuruganG** [comment]
@kvyatkovskys Thanks for the fix 👍🏻

**Comment by sabarics** [comment]
@kvyatkovskys Thanks for the new mode for week view. 👏👏👏
