### ISSUE TITLE
can we use event as the input parameter to the dequeueCell method

### ISSUE THREAD

**Issue by samulla** [kvyatkovskys/KVKCalendar#265]
Can we include the whole event object as the input of the
    func dequeueCell<T: UIScrollView>(dateParameter: DateParameter, type: CalendarType, view: T, indexPath: IndexPath) -> KVKCalendarCellProtocol?

This will help us from finding the right event from the event array in CalendarViewController. With the indexpath It is difficult to find the right item since we just have just array.

This is leading to wrong data in the list view cell.

Best regards,
Sami

**Comment by kvyatkovskys** [comment]
@samulla Hello!

hmm 🤔interesting point. I'll think about it.

**Comment by kvyatkovskys** [comment]
@samulla check this [branch](https://github.com/kvyatkovskys/KVKCalendar/pull/262) pls

**Comment by samulla** [comment]
> @samulla check this [branch](https://github.com/kvyatkovskys/KVKCalendar/pull/262) pls

@kvyatkovskys : This is good, I think just the Event parameter also would have worked instead of  CellParameter since the other fields are derived from the event only. If I am not wrong. Anyways, this will help.
