### ISSUE TITLE
ListView not scrolling to bottom

### ISSUE THREAD

**Issue by samulla** [kvyatkovskys/KVKCalendar#266]
I am using the list view in tab control. When I scroll to the bottom, the last cell are hidden behind the tab bar.

**Comment by kvyatkovskys** [comment]
Can you provide more details, pls? (video, screenshot)

**Comment by samulla** [comment]
<img width="328" alt="Scroll" src="https://user-images.githubusercontent.com/10658696/171366173-277881ea-893c-467e-820f-e50b1c3e5bca.png">

There is content for June 3 behind the tab at the bottom.

**Comment by virkrishna786** [comment]
Hi @kvyatkovskys   and also there is no metjhod expose for tableview for customFooterview .

**Comment by kvyatkovskys** [comment]
> Hi @kvyatkovskys   and also there is no metjhod expose for tableview for customFooterview . 
> 
> 

We can implement it 🙂

**Comment by kvyatkovskys** [comment]
> <img width="328" alt="Scroll" src="https://user-images.githubusercontent.com/10658696/171366173-277881ea-893c-467e-820f-e50b1c3e5bca.png">
> 
> 
> 
> There is content for June 3 behind the tab at the bottom.
> 
> 

What size of frame do you use?🤔

**Comment by kvyatkovskys** [comment]
Will try to reproduce this case

**Comment by kvyatkovskys** [comment]
@samulla couldn't reproduce this issue... perhaps, you need to change height of `calendarView` 🤔

https://user-images.githubusercontent.com/8233076/172463781-21e83038-2337-45b6-8f50-b14fbf7bcbb1.mov
