### ISSUE TITLE
Week-view does not scrolling to bottom

### ISSUE THREAD

**Issue by sabarics** [kvyatkovskys/KVKCalendar#267]
Week-view does not scroll to the bottom if have more the 15 events.

**Step to reproduce**
My events list
`{
    "data": [
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "401",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 1",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "402",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 2",
            "files": []
        }
        ,{
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "403",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 3",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "404",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 4",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "405",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 5",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "406",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 6",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "407",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 7",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "408",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 8",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "409",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 9",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "410",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 10",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "411",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 11",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "412",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 12",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "413",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 13",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "414",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 14",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "415",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 15",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "416",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 16",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "417",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 17",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "418",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 18",
            "files": []
        },
        {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c795",
            "end": "2022-06-02T09:00:00+03:00",
            "id": "419",
            "start": "2022-06-02T08:30:00+03:00",
            "text_color": "#000000",
            "title": "All day event number 19",
            "files": []
        }
    ]
}
`

**Screenshot**
<img src="https://user-images.githubusercontent.com/15062050/171613802-c41f193a-4bdd-46a1-a5dc-b1233c9bd0bc.png" data-canonical-src="https://user-images.githubusercontent.com/15062050/171613802-c41f193a-4bdd-46a1-a5dc-b1233c9bd0bc.png" width="200" height="400" />

**Comment by sabarics** [comment]
https://user-images.githubusercontent.com/15062050/171614813-0b56f073-b928-4e34-94a3-d7f095ce067a.mov

**Comment by kvyatkovskys** [comment]
I'll check this issue 😉

**Comment by sabarics** [comment]
@kvyatkovskys any update 😊?

**Comment by kvyatkovskys** [comment]
note yet, will try to check today later 😬

**Comment by sabarics** [comment]
Thanks 😊

**Comment by kvyatkovskys** [comment]
@sabarics couldn't reproduce this issue🤔 Could you check the new branch `feature/v_0.6.7`, pls?

**Comment by sabarics** [comment]
Thanks for the fix, now it's working :pray:

<img src="https://user-images.githubusercontent.com/15062050/172673008-02b4bfe1-deaf-49c2-baa5-6d48a808bacb.png" data-canonical-src="https://user-images.githubusercontent.com/15062050/172673008-02b4bfe1-deaf-49c2-baa5-6d48a808bacb.png" width="200" height="400" />

**Comment by sabarics** [comment]
> @sabarics couldn't reproduce this issue🤔 Could you check the new branch `feature/v_0.6.7`, pls?

Working 🙏
