### ISSUE TITLE
AllDay Even view scrolls behind to the top in timeline view

### ISSUE THREAD

**Issue by samulla** [kvyatkovskys/KVKCalendar#268]
The AllDay event view hides in the day view. It should always be visible on top, right?

https://user-images.githubusercontent.com/10658696/171842869-5a67b62a-284c-4603-91cb-f2c1bfb8c245.MP4

Best regards,
Sami

**Comment by kvyatkovskys** [comment]
Do you enable the property `style.allDay.isPinned`?

**Comment by kvyatkovskys** [comment]
I'll check this issue. Perhaps, problem with a top offset 🤔

**Comment by samulla** [comment]
you are right, my bad. 
style.allDay.isPinned did the trick

thanks a lot
