### ISSUE TITLE
MonthView can't refresh datasource after add or delete event 

### ISSUE THREAD

**Issue by ningmengjean** [kvyatkovskys/KVKCalendar#274]
**Describe the bug**
For example, first I have 10 events for dataSource, all the views can show correctly,  after **Add or  Delete one event**, use  `public func reloadData()`,  `dataSource?.eventsForCalendar(systemEvents: systemEvents)`  has correct number of events for dataSource, when switch to MonthView from other views , the MonthView can't refresh itself, it still has 10 events as usual, but DayView, WeekView and ListView are all correct  UI after the same operation(**Add or Delete one event**). `func getActualCachedDay(indexPath: IndexPath) -> MonthData.DayOfMonth` can't get the correct value in MonthData file. Would you please see this problem? Thanks a lot.

**Comment by kvyatkovskys** [comment]
Hello!

Can you provide more details, pls? I couldn't reproduce this issue

**Comment by ningmengjean** [comment]
Hello,
When I have 10 events for the dataSource first, every views can show 10 events correctly, but when I add a new event or delete one event from other views, I switch back to MonthView, MonthView can't show the right UI, 11 or 9 events(after add or delete event), but other views (DayView, WeekView, ListView) all can show the correct UI. DataSource is correct from `public func reloadData(), dataSource?.eventsForCalendar(systemEvents: systemEvents)`, but  `func getActualCachedDay(indexPath: IndexPath) -> MonthData.DayOfMonth` is not right.

**Comment by ningmengjean** [comment]
10 events for dataSource -> All UI are correct. -> Add or Delete events -> Switch to every view -> DayView, WeekView, ListView are correct, MonthView is not right.
Refresh dataSource for all the views are correct, MonthView can't refresh itself with right dataSource, it still show the old cache.

**Comment by ningmengjean** [comment]
Sorry, I used your old version of KVKCalendar, you fix this issue already. Really sorry for your time.
