### ISSUE TITLE
weekheaderview shifted to right 

### ISSUE THREAD

**Issue by virkrishna786** [kvyatkovskys/KVKCalendar#277]
[
![IMG_253FBDA5730D-1](https://user-images.githubusercontent.com/16114706/182813724-358baa54-5fb2-4ccf-b7af-913a7584a2b6.jpeg)
](url)

Hi @kvyatkovskys 

Could you please check why this weekview shifted to right or is there any property by which we can adjust frame for header weekview

**Comment by kvyatkovskys** [comment]
this issue will be fixed in the next release `v. 0.6.9`
