### ISSUE TITLE
Load more events in list view 

### ISSUE THREAD

**Issue by virkrishna786** [kvyatkovskys/KVKCalendar#282]
**Describe the bug**
Hi 

I am working on loading more events for customer for upcoming dates 
so currently i am fetching the events from api for upcoming one month . 

So could you please tell me is there any method exposed for loading more events in list so that i can use it .

I think there should be some public method for headerforsectionview in list so that we can check the date and call the api again 
if it is already exposed then please  tell me . 

Thanks & Regards
Krishan

**Comment by kvyatkovskys** [comment]
Hello!

I'll add a new method to check when the user scrolls to the end of the list.

**Comment by virkrishna786** [comment]
@kvyatkovskys thank you

**Comment by kvyatkovskys** [comment]
FYI, the `ListView.swift` is a public file. You can work with list as you wish. 🙂
