### ISSUE TITLE
On creating event from DayView does not give exact time on long press 

### ISSUE THREAD

**Issue by virkrishna786** [kvyatkovskys/KVKCalendar#284]
Hi @kvyatkovskys 

I am trying to add event from long press gesture from dayview on particular time . 

So If i am selecting 3 am . then when  i am checking the selected time in this given method 

func didAddNewEvent(_ event: Event, _ date: Date?) {}

but it is showing 2: 15  am . I think it is not picking correct locatin of time on timeline 

Could you please check this behaviour 

Thanks & regards
Krishan vir singh

**Comment by kvyatkovskys** [comment]
Thx for the issue. I'll check

**Comment by kvyatkovskys** [comment]
couldn't reproduce... works fine for me
