### ISSUE TITLE
List View upgrade 

### ISSUE THREAD

**Issue by virkrishna786** [kvyatkovskys/KVKCalendar#287]
Hi @kvyatkovskys 

There are two issues i am facing on list view . 
![IMG_B0B05C42C6E2-1](https://user-images.githubusercontent.com/16114706/192693931-742119ec-e842-4a76-8bc3-cbf8e2eab203.jpeg)
![Simulator Screen Shot - iPhone 14 - 2022-09-28 at 09 38 21](https://user-images.githubusercontent.com/16114706/192693940-21663e08-11e1-4dd8-89b4-ac2eddbee413.png)

1. In First Screen shot you can see list sector header date format is in Capital letter can we achive it . 
2. In Second screen shot i am not able to put any divider in sector header to differentiate from list cell .

**Comment by kvyatkovskys** [comment]
Hi @virkrishna786!

You can create your own custom header view for each section, just to use this function 
`    func dequeueHeader<T: UIScrollView>(date: Date?, type: CalendarType, view: T, indexPath: IndexPath) -> KVKCalendarHeaderProtocol?
`
