### ISSUE TITLE
Show all events for all months, MonthView style

### ISSUE THREAD

**Issue by yuriypashkov** [kvyatkovskys/KVKCalendar#288]
Hi @kvyatkovskys
I'm using your calendar (version 0.6.9) in my app, with MonthView style.
I'm need showing all events for all months.
Ok, set style-property **style.month.autoSelectionDateWhenScrolling = true** and implement CalendarDelegate method
```
    func willSelectDate(_ date: Date, type: CalendarType) {
        calendarView.reloadData()
    }
```
And calendar not works correct. Sometimes date selected when scrolling (events loaded), sometimes not (events not loaded).

You can see this on video:
https://www.youtube.com/watch?v=HQd2nqZUqCM

Is there another way to display all events for all months? 

Thank you

**Comment by kvyatkovskys** [comment]
Hi @yuriypashkov! I'll check this case, thx for the issue.

**Comment by kvyatkovskys** [comment]
Hi @yuriypashkov! will be fixed in the ver. 0.6.10

**Comment by yuriypashkov** [comment]
That's cool! Thank you very much :)
