### ISSUE TITLE
Missing vertical lines at week view

### ISSUE THREAD

**Issue by AentZ-eu** [kvyatkovskys/KVKCalendar#295]
**To Reproduce**
1. Create new project (SwiftUI)
2. Add package (using Swift Package Manager)
3. Use sample code from [README](https://github.com/kvyatkovskys/KVKCalendar#usage-for-swiftui)
5. Style settings for CalendarView
````
    private var calendar: CalendarView = {
        var style = Style()
        style.defaultType = .week
        style.timeSystem = .twentyFour

        return CalendarView(frame: UIScreen.main.bounds, style: style)
    }()
````
1. Slide between weeks

**Expected behavior**
Show vertical lines at every week.

**Screenshots**
![Screen-Recording-2022-11-07-at-12 36 22](https://user-images.githubusercontent.com/95862003/200302455-b73abc04-53e6-4579-92d3-36c298f19936.gif)

**Comment by kvyatkovskys** [comment]
Hello @AentZ-eu!

Could you check on real device? I could't reproduce this issue

**Comment by AentZ-eu** [comment]
Thank you for your quick response!

I tried it on iPad Air 4. iPadOS 16.1.
There I have the same problem.

![IMG_D2CA3818D086-1](https://user-images.githubusercontent.com/95862003/200346311-163d6510-857d-4af3-b504-66fe2af5d1a0.jpeg)
![IMG_6940A0540F7E-1](https://user-images.githubusercontent.com/95862003/200346300-9a1452a4-8022-4a59-8bf7-fc940fee2570.jpeg)
![IMG_6940A0540F7E-2](https://user-images.githubusercontent.com/95862003/200346283-c827f899-2c13-458f-abab-34aefa87e343.jpeg)

**Comment by kvyatkovskys** [comment]
@AentZ-eu Hello

I couldn't reproduce it on may devices... need time to investigate

**Comment by AentZ-eu** [comment]
@kvyatkovskys thank you!

Maybe this helps, I also tried a lower iOS version with the same problem.

![Screen-Recording-2022-11-10-at-09 19 31](https://user-images.githubusercontent.com/95862003/201038998-010318a1-77c8-4f1d-882d-71c7593242c7.gif)

**Comment by kvyatkovskys** [comment]
@AentZ-eu Hello!

I have checked the SwiftUI example and no problems... will try to investigate this issue.
BTW, the SwiftUI example is not a good 😬... will add more changes for the example

**Comment by kvyatkovskys** [comment]
I checked this issue on the example from this [branch](https://github.com/kvyatkovskys/KVKCalendar/tree/feature/v_0.6.12) and works fine for me 🤔

**Comment by AentZ-eu** [comment]
Thank you for your help! With the updated examples I was able to solve the problem. It seems to have been an initialization error.

Using your examples I had trouble adding/modifying events. It looks like the `events` are not changed in  the `view`. (`view.events.append`).

![Screenshot 2022-11-16 at 15 46 43](https://user-images.githubusercontent.com/95862003/202212219-b1cfcc3f-d013-4960-bd57-2d0b5c84712f.png)

**Comment by kvyatkovskys** [comment]
@AentZ-eu I have added more fixes for the example and I'm still working on it..... if it helps you 🙂

**Comment by AentZ-eu** [comment]
This helps! My Problem is solved, thank you.
