### ISSUE TITLE
Lazy Loading of agenda view 

### ISSUE THREAD

**Issue by virkrishna786** [kvyatkovskys/KVKCalendar#297]
Hi @kvyatkovskys 

i am trying to load more than 500 events on listview . but it is taking time to show on UI Side . 

is there any way by which we can make it in chunks or like lazy loading of events . 

At one time it will load  only 20-30  records . so The response time for loading list should be less.

Thanks & Regards
Krishan vir Singh

**Comment by kvyatkovskys** [comment]
Hello @virkrishna786 

hmm, perhaps we can add loading of events in parts 🤔

**Comment by virkrishna786** [comment]
thank you @kvyatkovskys

**Comment by virkrishna786** [comment]
Hi @kvyatkovskys  

how can we add loading of events in parts  . suppose we have more than 500 events at a time of api call .?

**Comment by sabarics** [comment]
@kvyatkovskys  @virkrishna786 did you get any solution. I want to make api call for each month in list view. How can I achieve this? Is there any delegate to get event in list view?

**Comment by kvyatkovskys** [comment]
@sabarics Hello! I plan to open the `ListView` with opened tableView methods `UITableViewDataSource, UITableViewDelegate`... you will be able to override any one

**Comment by sabarics** [comment]
@kvyatkovskys thanks for thé replay. When can I expect that release? Also by using UItableview delegate and data source how can I know dates to get data? In month view we have a delegate so it's working fine. The same how can I use it for the list view? I want to load the last 12 months and the future 12 months events in the list view. Each month I have n number of events so here I need the pagination to refresh data for each month.

**Comment by kvyatkovskys** [comment]
New release `0.6.15` will be available on next week. I'll add new method to get list of events on `ListView`

**Comment by sabari-zuper** [comment]
@kvyatkovskys Thanks for the update.

**Comment by sabari-zuper** [comment]
@kvyatkovskys When can I expect the new release `0.6.15`

**Comment by kvyatkovskys** [comment]
> @kvyatkovskys When can I expect the new release `0.6.15`

This week or weekend, thx

**Comment by sabari-zuper** [comment]
@kvyatkovskys any update on new release `0.6.15`

**Comment by kvyatkovskys** [comment]
> @kvyatkovskys any update on new release `0.6.15`

Will release today, thx

**Comment by sabari-zuper** [comment]
@kvyatkovskys thanks for the update

**Comment by kvyatkovskys** [comment]
to get list of items in ListView
`func willDisplaySectionsInListView(_ sections: [ListViewData.SectionListView])`

**Comment by sabari-zuper** [comment]
@kvyatkovskys How can I retrieve the date? For example, if I am in the list view, I want to make an API call for each month to retrieve the events specific to that month. How can I accomplish this?

**Comment by kvyatkovskys** [comment]
> @kvyatkovskys How can I retrieve the date? For example, if I am in the list view, I want to make an API call for each month to retrieve the events specific to that month. How can I accomplish this?

Use the opened methods from ListView
Like `willDisplayCell`

**Comment by sabari-zuper** [comment]
@kvyatkovskys  There is no method like `willDisplayCell` in list view
