### ISSUE TITLE
didChangeEvent returns wrong (number of month) when drag event at the junction of the months

### ISSUE THREAD

**Issue by IvanKopych** [kvyatkovskys/KVKCalendar#299]
Describe the bug
When I try to drag the event from November 29 to December 2, methods didChangeEvent returns
start: 2022-11-02 11:00:00,
end: 2022-11-02 12:00:00.

But I expected
start: 2022-12-02 11:00:00
end: 2022-12-02 12:00:00.

number of the month doesn't change

To Reproduce

Book an event on any 28, 29, or 30 dates of any month
Drag this event to next month 1, 2, or 3 date
See the error
Expected behavior
The correct number of the month

Screenshots 
<img width="1051" alt="Screenshot 2022-11-28 at 12 13 08" src="https://user-images.githubusercontent.com/21034852/204255461-53d94693-6fee-4b50-b7c5-fec929a0256b.png">

**Comment by kvyatkovskys** [comment]
Hello @IvanKopych 

Thx for the issue! I'll take a look.
