### ISSUE TITLE
what is year in KVKCalendarView init?

### ISSUE THREAD

**Issue by samulla** [kvyatkovskys/KVKCalendar#304]
Hi,
I want to know the significance of the new parameter "year", and why it is not optional.

public init(frame: CGRect, date: Date? = nil, style: Style = Style(), years: Int = 4)

What should I pass for year parameter?

Best regards,
Sami

**Comment by kvyatkovskys** [comment]
Hello @samulla!

This is the old parameter describing count of year in calendar.
