### ISSUE TITLE
date selection of agenda view section header can be disabled 

### ISSUE THREAD

**Issue by virkrishna786** [kvyatkovskys/KVKCalendar#312]
Hi @kvyatkovskys 

This happens every time when we click on section header in agenda view . 
So the date which has events should not be clickable . 

because every time when we click on sectin header date it reloads the data .

Could you please tell us any way  to disable this

**Comment by kvyatkovskys** [comment]
Hello!

Are you talking about listView?

**Comment by virkrishna786** [comment]
@kvyatkovskys  yes please suggest me the solution as i click on section date header in agenda view . It is performing actions . So please tell me how we can disable this . or block the click event

**Comment by kvyatkovskys** [comment]
@virkrishna786 so you can disable reload in `func didSelectDates(_ dates: [Date], type: CalendarType, frame: CGRect?)` just check the `type` inside
