### ISSUE TITLE
Getting Errors While Running the Project After Pod install

### ISSUE THREAD

**Issue by mohitordex** [kvyatkovskys/KVKCalendar#315]
**Describe the bug**
I have downloaded the project and install the pod using "pod install" command after that when i try to run the app, it is giving errors

**To Reproduce**

**Expected behavior**
App should be run without Errors

**Sc
![Screenshot 2023-04-28 at 12 09 41 PM](https://user-images.githubusercontent.com/111515330/235073733-dbeb8b61-823f-4036-a916-39854be7bab7.png)
reenshots**

**Additional context**

**Comment by kvyatkovskys** [comment]
Hello!
What version of the library do you use?

**Comment by mohitordex** [comment]
Hello Sir, I have used the master branch!

**Comment by kvyatkovskys** [comment]
I see on screenshot you use the not released version from branch `feature/`. You should switch on release version `ver. 0.6.13`

**Comment by mohitordex** [comment]
Hi I have checked both master and feature version 0.6.14, In both i am getting errors.

Can you guide me, Where shall i download ver.0.6.13 :
![Screenshot 2023-04-28 at 12 25 13 PM](https://user-images.githubusercontent.com/111515330/235076720-f551db29-3394-4054-ba79-bc746f3e798c.png)

**Comment by mohitordex** [comment]
![Screenshot 2023-04-28 at 12 29 22 PM](https://user-images.githubusercontent.com/111515330/235077248-7047898e-0541-44cc-b569-a9a0ae546927.png)
Please look also getting error in master branch.

**Comment by kvyatkovskys** [comment]
pod is good
<img width="1091" alt="Screenshot 2023-05-07 at 12 35 50 AM" src="https://user-images.githubusercontent.com/8233076/236647579-8df3bc62-bd65-410f-b8eb-e8cd50b65e1a.png">

**Comment by kvyatkovskys** [comment]
looks like issue with the old version of Xcode
