### ISSUE TITLE
Crash in year view when the view height is small

### ISSUE THREAD

**Issue by phuanggh** [kvyatkovskys/KVKCalendar#318]
**Describe the bug**
Crash happens when the height of the calendar view is set to be 5

**Root cause**
YearView.swift: 232
when height < data.style.year.heightTitleHeader, crash will happen

```
  if height > 0 {
      height -= data.style.year.heightTitleHeader
  }
```

**To Reproduce**
1. set the height to 5 and reload frame
2. crash

**Expected behaviour**
The app should not crash when the height of the view is set to be a small value

**Screenshots**

**Additional context**
version: 0.6.15
Error message:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Collection view delegate returned a negative size {245, -11.25} from -collectionView:layout:sizeForItemAtIndexPath: for item 0 in section 0, which is not supported by flow layout. Delegate: <KVKCalendar.YearView: 0x7f7bd328b3a0; frame = (0 0; 750 5); backgroundColor = <UIDynamicProviderColor: 0x60000040d0c0; provider = <__NSMallocBlock__: 0x600000a868b0>>; layer = <CALayer: 0x6000004e83c0>>; collection view: <UICollectionView: 0x7f7bd516f200; frame = (0 0; 750 5); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600000b58180>; backgroundColor = <UIDynamicProviderColor: 0x60000040d0c0; provider = <__NSMallocBlock__: 0x600000a868b0>>; layer = <CALayer: 0x60000050b060>; contentOffset: {0, 305}; contentSize: {750, 1220}; adjustedContentInset: {0, 0, 0, 0}; layout: <UICollectionViewFlowLayout: 0x7f7bd328b560>; dataSource: <KVKCalendar.YearView: 0x7f7bd328b3a0; frame = (0 0; 750 5); backgroundColor = <UIDynamicProviderColor: 0x60000040d0c0; provider = <__NSMallocBlock__: 0x600000a868b0>>; layer = <CALayer: 0x6000004e83c0>>>'

**Comment by kvyatkovskys** [comment]
Hello @phuanggh!  
Thank you for the issue. I'll take a look.

**Comment by phuanggh** [comment]
temporarily solved the crash by this

`style.year.heightTitleHeader = 0`
