### ISSUE TITLE
Missing part of day

### ISSUE THREAD

**Issue by teonji** [kvyatkovskys/KVKCalendar#33]
how can i show all the morning area in case first event fetched in the day start in the afternoon?
<img width="389" alt="Schermata 2019-12-30 alle 19 16 36" src="https://user-images.githubusercontent.com/1690632/71594716-4640bf00-2b39-11ea-8120-a877fae6b7d6.png">
thanks

**Comment by kvyatkovskys** [comment]
The `Timeline` is shown from the beginning of the first event. You wanna show all empty hours?

**Comment by teonji** [comment]
yep, would be awesome if is possible! or it can could be a Style option :)
Sorry if I'm boring you with this 🙂

**Comment by kvyatkovskys** [comment]
🤔 I’ll think about it)

**Comment by kvyatkovskys** [comment]
Hi)
I added a new property to style `timeline.startFromFirstEvent`. You can set `false` to see all day in time line. (v. 0.2.4)

**Comment by anandabayu** [comment]
> timeline.startFromFirstEvent

Hi, I can't find `timeline.startFromFirstEvent` on the newest update

**Comment by kvyatkovskys** [comment]
> > timeline.startFromFirstEvent
> 
> Hi, I can't find `timeline.startFromFirstEvent` on the newest update

What version do you use? CocoaPods? Carthage?

**Comment by anandabayu** [comment]
> > > timeline.startFromFirstEvent
> > 
> > 
> > Hi, I can't find `timeline.startFromFirstEvent` on the newest update
> 
> What version do you use? CocoaPods? Carthage?

I use pod, `pod 'KVKCalendar'` so I guess it the latest version

**Comment by anandabayu** [comment]
I just install 0.2.5 version and everything is oke now 😁
