### ISSUE TITLE
Bitrise build swift compiler error 

### ISSUE THREAD

**Issue by kumararun5400** [kvyatkovskys/KVKCalendar#333]
**Describe the bug**
Swift Compiler Error (Xcode): Reference to property 'collectionView' in closure requires explicit use of 'self' to make capture semantics explicit
git/ios/Pods/KVKCalendar/Sources/KVKCalendar/MonthView.swift:114:56
 
**To Reproduce**
Building app with bitrise and getting this error. 

**Expected behavior**
It should build successfully.

**Comment by kvyatkovskys** [comment]
Hello @kumararun5400! Can you provide more details pls?

**Comment by kumararun5400** [comment]
Hi @kvyatkovskys, 
We are trying to setup [bitrise](https://bitrise.io/) builds, getting following error. 
Swift Compiler Error (Xcode): Reference to property 'collectionView' in closure requires explicit use of 'self' to make capture semantics explicit
git/ios/Pods/KVKCalendar/Sources/KVKCalendar/MonthView.swift:114:56
<img width="1255" alt="iOS_Bitrise" src="https://github.com/kvyatkovskys/KVKCalendar/assets/21003727/23ee798e-3093-4e20-965c-88a4051e72fd">
Its related to memory - https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/
Please let me know if you need more info.

**Comment by kvyatkovskys** [comment]
Thx for the details. One more question:
- What version of Xcode are you using?

I think, the old one 🤔
