### ISSUE TITLE
StoryBoard

### ISSUE THREAD

**Issue by justdan0227** [kvyatkovskys/KVKCalendar#34]
How do you use this in a story board?

**Comment by kvyatkovskys** [comment]
You mean to set up a style in interface builder in real time?

**Comment by justdan0227** [comment]
I mean use storyboard to place the calendar and then when the view loads add the styling.  I have a complicated screen and the calendar needs to take up 1/2 of the screen.  I can put a UIView in the storyboard as a place holder and then just add the calendarview to it but wanted to know if there was a simpler way.

**Comment by kvyatkovskys** [comment]
At present the library doesn't support `Storyboard` in full.

**Comment by justdan0227** [comment]
Really a great library.  Any word on if we can get storyboard support?

**Comment by kvyatkovskys** [comment]
I need more time to get storyboard support)

**Comment by justdan0227** [comment]
So just to let everyone know, I created a UIView in my storyboard and then simply set the calendar view to it in code
