### ISSUE TITLE
Example Selected Date

### ISSUE THREAD

**Issue by justdan0227** [kvyatkovskys/KVKCalendar#35]
Having an issue in my app so I went to the example.  What am I missing in that when you select a date in the Example and then switch from day to month to week, that the selected date keeps changing.  Also, TODAY is off by one and I have to add 

```
var today = Date()
today = today.addingTimeInterval(86400)
```

**Comment by kvyatkovskys** [comment]
I'll check.

**Comment by justdan0227** [comment]
Any update?  So I'm in Chicago TZ -6.0 and yet when I click on didSelectDate it gives me the next day?  Clicking on the 24th in a month view will return the 25th?

**Comment by kvyatkovskys** [comment]
Not yet. I’ll try to reproduce with your time zone and fix it as soon as possible.

**Comment by kvyatkovskys** [comment]
Issue is fixed (v. 0.2.4)

**Comment by justdan0227** [comment]
Awesome!  Thanks!
