### ISSUE TITLE
how to disable timeline scrolling left and right

### ISSUE THREAD

**Issue by sg192** [kvyatkovskys/KVKCalendar#362]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kvyatkovskys** [comment]
Hey @sg192! 
Try to use this `style.timeline.scrollDirections = [.vertical]`

**Comment by shilpagade** [comment]
> Hey @sg192! Try to use this `style.timeline.scrollDirections = [.vertical]`

thanks

**Comment by shilpagade** [comment]
<img width="344" alt="Image" src="https://github.com/user-attachments/assets/b28d7df7-4497-45c1-9e36-bd75751f95dc" />
Can we get click from time line ?
