### ISSUE TITLE
movingCurrentLineHour crashing on xcode 11.3.1

### ISSUE THREAD

**Issue by justdan0227** [kvyatkovskys/KVKCalendar#37]
The following line is crashing on a minute update at guard let time =
    
private func movingCurrentLineHour() {
        guard !(timer?.isValid ?? false) else { return }
        
        let date = Date()
        var comps = style.calendar.dateComponents([.era, .year, .month, .day, .hour, .minute], from: date)
        comps.minute = (comps.minute ?? 0) + 1
        guard let nextMinute = style.calendar.date(from: comps) else { return }
        
        timer = Timer(fire: nextMinute, interval: 60, repeats: true) { [unowned self] _ in
            let nextDate = Date()
            guard let time = self.getTimelineLabel(hour: nextDate.hour) else { return }

**Comment by kvyatkovskys** [comment]
🤔 Do you use the framework in UIKit or SwiftUI?

**Comment by justdan0227** [comment]
Framework, no swiftUI, Swift 4.0 - 
UPDATE:  What is odd is that if I attempted to change the 60 to 5 as I was going to try and debug, it would ask if I wanted to unlock the file (since it’s a pod).  I said yes and changed it to 5.  Ran the app and it worked.  Thought that's odd, so changed it back to 60.  Now it works??

**Comment by kvyatkovskys** [comment]
🤔 I'll try to repeat and fix it on this weekend and update a framework. Thx for your report)

**Comment by kvyatkovskys** [comment]
Issue is fixed (v. 0.2.4)
