### ISSUE TITLE
Add event 

### ISSUE THREAD

**Issue by vids123** [kvyatkovskys/KVKCalendar#45]
Can we add event by clicking on particular date range for Day/Week view like we do in Apple default calendar?

**Comment by kvyatkovskys** [comment]
Hi)
To create a new event?

**Comment by vids123** [comment]
Yes.

**Comment by kvyatkovskys** [comment]
🤔 yes we can)

**Comment by vids123** [comment]
Can you please let me know any delegate method for the same??

**Comment by kvyatkovskys** [comment]
No) I'll need to write a new method. It will be done in next release.

**Comment by vids123** [comment]
Okay.
Thanks for your quick response.

**Comment by kvyatkovskys** [comment]
Added an optional method `didAddEvent(_ date: Date?)` to v.0.2.6
