### ISSUE TITLE
Events in UTC - Local

### ISSUE THREAD

**Issue by justdan0227** [kvyatkovskys/KVKCalendar#46]
I'm assuming that Events are in UTC right?  If I want to create an event for today, Central Time for 8.am ( or 8am for whatever timezone the phone is currently in), what do I use for an event start date object?

**Comment by kvyatkovskys** [comment]
🤔you need to create events with an offset `UTC -6` (CST)
example:
` "start": "2020-02-12T08:00:00-06:00", "end": "2020-02-12T08:30:00-06:00"`
