### ISSUE TITLE
Problem with displaying and loading events in "Week" section

### ISSUE THREAD

**Issue by Saloukai** [kvyatkovskys/KVKCalendar#47]
Having an issue in week section to load and display events.
Imagine we have an event on Tuesday February 18 and another on Tuesday February 25. The current day is Tuesday 18, so the first event is well displaying but when i change the week (with the Tuesday 25), the second event isn't displaying and if i click on my view and i begin to slide, the first event (Tuesday 18) is displaying for the Tuesday 25. (same for any weeks)

Only events from current week is displaying. See example (gif)
I followed the example in the readme to write my code.

![calendar_issue](https://user-images.githubusercontent.com/13482883/74720445-1e670100-5236-11ea-93d4-c7ee8daaa214.gif)

**Comment by kvyatkovskys** [comment]
🤔 very strange... What version do you use?
I'll try to reproduce the issue.

**Comment by Saloukai** [comment]
I use version 0.2.5
Ok, thank's 👍

**Comment by dokoeur** [comment]
Hi,

i reproduce the same issue in version **0.2.6** 

Edit : after added `calendar.reloadData()` in `didSelectDate(Date?,CalendarType, CGRect?)` the list is updated as expected

**Comment by kvyatkovskys** [comment]
🤔

**Comment by Saloukai** [comment]
> Hi,
> 
> i reproduce the same issue in version **0.2.6**
> 
> Edit : after added `calendar.reloadData()` in `didSelectDate(Date?,CalendarType, CGRect?)` the list is updated as expected

**Comment by Saloukai** [comment]
@dokoeur I try to reload data in didSelectDate function, but this function is never called..

**Comment by dokoeur** [comment]
@Saloukai Did you set the CalendarDelegate ?

**Comment by Saloukai** [comment]
My bad, the function prototype was wrong.
It works, thx @dokoeur !
I close this issue.
