### ISSUE TITLE
Event view column size

### ISSUE THREAD

**Issue by anandabayu** [kvyatkovskys/KVKCalendar#48]
Hi, how can I fix the event width to the full width of the frame, if I don't have any event with the same hours?
I've 3 data and my event width looks like divided with event count.

I want the event size divide by the amount of event with the same hours only, not all events.

Edit: I used v0.2.5

![IMG_306FB7CD49EB-1](https://user-images.githubusercontent.com/9120244/74847688-1bb6f980-5365-11ea-9d39-ab7871ae883c.jpeg)

**Comment by kvyatkovskys** [comment]
Hi, need to check `TimelineView.swift`... where the width is calculated. 🤔

**Comment by anandabayu** [comment]
Hi, I realize it happens because my date was greater than 1 day.

start: 2020-02-19 10:00:00
end: 2020-02-20 15:00:00

if the start and end date are the same, the width will full.

I hope this can be handled with a different start date and end date.

**Comment by TToldi** [comment]
Hi,
Just a quick question.. I noticed that when you have more than 2 events in the same 'Hour/multiple hours' you start to get the same effect (The white space on the right).
Is it just me, or is this how it works? Believe it has something to do with the "countEventsInHour" function, maybe the +1? not quite sure
Would really appreciate it if you could let me know... If i figure it out I'll post it here too!

**Comment by TToldi** [comment]
Just had another thought.. I believe it is calculating all the events between the start of the first event which is overlapping and the last ending event... so if you have multiple i.e 9 events in the space of 2/3 hours however within the first hour you only  have 5 then you should get 5 columns and not 9... but at the moment you have 4 extra white spaces... Probably sounds a bit confusing, sorry!

**Comment by kvyatkovskys** [comment]
> Just had another thought.. I believe it is calculating all the events between the start of the first event which is overlapping and the last ending event... so if you have multiple i.e 9 events in the space of 2/3 hours however within the first hour you only have 5 then you should get 5 columns and not 9... but at the moment you have 4 extra white spaces... Probably sounds a bit confusing, sorry!

Hello, 

You're right. I'm still working on improving the algorithm for calculating width of events in the same hour.
Perhaps, you have an event with a long duration. 
Can you send the time of the events? I'll check.

**Comment by TToldi** [comment]
Thanks for the reply!
I have just tried with these times and I get the same issue... I think maybe it would be good if they were added 1 after the other... at the moment it will insert the event in a gap if the time is free..
             -Start.                        -End
            "2020/05/19 12:00": "2020/05/19 15:00",
            "2020/05/19 11:45": "2020/05/19 14:30",
            "2020/05/19 12:45": "2020/05/19 15:30",
            "2020/05/19 15:05": "2020/05/19 16:30",
            "2020/05/19 10:45": "2020/05/19 12:30",
            "2020/05/19 10:25": "2020/05/19 14:30"

**Comment by TToldi** [comment]
Hello! Sorry to ask, is there any chance you have had a look at this? I still cant figure it out, not quite sure what is causing the issue

**Comment by anandabayu** [comment]
> Hello! Sorry to ask, is there any chance you have had a look at this? I still cant figure it out, not quite sure what is causing the issue

Hi, can you attach the screenshot and the code? maybe I can help
