### ISSUE TITLE
Month View Day icon getting cut off

### ISSUE THREAD

**Issue by justdan0227** [kvyatkovskys/KVKCalendar#49]
![Screen Shot 2020-02-28 at 9 58 17 AM](https://user-images.githubusercontent.com/918740/75564180-45c98500-5a11-11ea-8f2c-d6a643b80498.png)
Thoughts as to how to fix the fact that the current-day icon is getting chopped off when we switch to Month View?

**Comment by kvyatkovskys** [comment]
here? <img width="627" alt="Screenshot 2020-02-29 at 16 24 32" src="https://user-images.githubusercontent.com/8233076/75608394-0f266400-5b10-11ea-9a4a-311fc75013a5.png">

**Comment by justdan0227** [comment]
No the red circle around the 28th.. If I select any date in the middle it too is cut off (the red circle)

**Comment by kvyatkovskys** [comment]
I see, I'll fix it in the next version, thx)

**Comment by justdan0227** [comment]
BTW, I am creating this with Storyboard using a UIView as a place holder and then placing the calendarview in it.

**Comment by kvyatkovskys** [comment]
Issue is fixed in v0.2.7
