### ISSUE TITLE
Events for a date

### ISSUE THREAD

**Issue by justdan0227** [kvyatkovskys/KVKCalendar#50]
Can you get all of the events for a selected date (other than iterating through them)?

**Comment by kvyatkovskys** [comment]
filter array of events by selected date)

**Comment by kvyatkovskys** [comment]
copy https://github.com/kvyatkovskys/KVKCalendar/issues/56

**Comment by kvyatkovskys** [comment]
Added new method func didDisplayEvents(_ events: [Event], dates: [Date?]) to CalendarDelegate to v0.2.8
