### ISSUE TITLE
Does not conform to protocol

### ISSUE THREAD

**Issue by bitdelve** [kvyatkovskys/KVKCalendar#51]
extension JobDetailsViewController: CalendarDataSource {
    func eventsForCalendar() -> [Event] {
        return events
    }   
}

This is the code for the data source, but I get the 'Does not conform to protocol' error.  Any thoughts?

**Comment by kvyatkovskys** [comment]
Hi)
Do you need to subscribe to protocol in `JobsDetailViewController`.
ex. `calendar.datasource = self`

**Comment by bitdelve** [comment]
That is there, too. It is really weird, because I created a test project and it works in that, but not in my main project. I have no clue what it could be.

**Comment by bitdelve** [comment]
@kvyatkovskys This is happening while building, not a runtime error. So even if I hadn't set the delegate I shouldn't see that error.  Another error I see is 

Candidate has non-matching type '() -> [Event]'

**Comment by kvyatkovskys** [comment]
Can you show me your code?

**Comment by bitdelve** [comment]
@kvyatkovskys  The workaround I found was to just copy the files into my project instead of using the pod. I think there is something messed up with the pod, likely for my project, because I could use the pod in a fresh project and it worked fine. Also worked fine with your example.

**Comment by kvyatkovskys** [comment]
🤔 so, you just copied the files to project manually? without CocoaPods or Carthage

**Comment by bitdelve** [comment]
@kvyatkovskys Right. I did find the actual solution, though. I cleared the cocoapods cache and installed the pod again and it worked. So it was an issue on my end.

**Comment by kvyatkovskys** [comment]
Cool)
