### ISSUE TITLE
Is it possible to make a List View?

### ISSUE THREAD

**Issue by jamal-pasha** [kvyatkovskys/KVKCalendar#52]
First of all thank you for such a great plugin. I need to make a list view like a UITableView tab next to month tab. I will really appreciate the help or at least the guidance on how to do that.

**Comment by kvyatkovskys** [comment]
Hi, thx)🙂
What do you want to do with the list? (just to display list of events 🤔)

**Comment by jamal-pasha** [comment]
Hi Thank you for the response. I have some events marked as important. they can be in Future too. I need a list view where I can show them the events in a table format rather than user swipes through the whole calender. 
I have been using Js Calender which is almost same as your calender and there I have an option of list view.

**Comment by kvyatkovskys** [comment]
can you send a screenshot? What it looks like. 🙂

**Comment by jamal-pasha** [comment]
Sure 
![Bildschirmfoto 2020-03-06 um 14 30 01](https://user-images.githubusercontent.com/7863262/76087799-2a352000-5fb7-11ea-9959-c143c1eff357.png)

**Comment by jamal-pasha** [comment]
Write now I have made an Separate Table view where I am showing the events, but user has to click on the icon and go to Table view and then come back to calender

**Comment by kvyatkovskys** [comment]
ok, thx)
I'll try to add a new enhancement in the next version.

**Comment by jamal-pasha** [comment]
Thanks. It will a great enhancement for the plugin.

I have one more question, if you can answer here

**Comment by bitdelve** [comment]
What is the status if this enhancement?

**Comment by kvyatkovskys** [comment]
I plan to release this enhancement in the next release `v0.4.4`

**Comment by jamal-pasha** [comment]
@kvyatkovskys Thanks. Looking forward for this enhancement
