### ISSUE TITLE
On Monthly view events are not selectable or titled.

### ISSUE THREAD

**Issue by chrisvoronin** [kvyatkovskys/KVKCalendar#54]
Hi,

In the example on a daily view I can select an event, even drag it.  However, on monthly view events are not selectable (just shows multi color dots).  Tapping on the event dots in monthly view does not trigger delegate callbacks.

Is it possible to update those dots to show actual titles instead, and to do delegate callbacks on selection?
Does this need a code update, or is this functionality already available and I'm just not aware of it?

Thanks,

Chris

**Comment by kvyatkovskys** [comment]
Hi)
I'll check it and add an additional callback

**Comment by kvyatkovskys** [comment]
Try using v0.2.7... I added some small corrections.

**Comment by chrisvoronin** [comment]
Thanks
