### ISSUE TITLE
Get events on calendar view

### ISSUE THREAD

**Issue by bitdelve** [kvyatkovskys/KVKCalendar#56]
Is it possible to get events that are visible on the calendar? For instance Just what you see on the week view?

**Comment by kvyatkovskys** [comment]
🤔 At present, you need to filter list of events by dates....
Perhaps, I can add an additional method to get events for (day, week, month) views

**Comment by bitdelve** [comment]
@kvyatkovskys that would be great if you could add a method for that. For now I will filter. Thanks

**Comment by kvyatkovskys** [comment]
Added new method func didDisplayEvents(_ events: [Event], dates: [Date?]) to CalendarDelegate to v0.2.8
