### ISSUE TITLE
Contraints?

### ISSUE THREAD

**Issue by justdan0227** [kvyatkovskys/KVKCalendar#57]
How are constraints dealt with in the calendar?  I've been using an iPhone and its working just great.  However one of my users tried it on an iPad, and when they switch to month view the view is all messed up.  How do we use this the calendar does not take up the entire screen?

**Comment by kvyatkovskys** [comment]
The library uses manual layout. There may be a problem with storyboard and constraints. 🤔 I haven’t add storyboard support to the library.

**Comment by justdan0227** [comment]
Let's track this under issue 34 :)
