### ISSUE TITLE
Can i change position of date from vertical to horizontal?

### ISSUE THREAD

**Issue by krutitrivedi** [kvyatkovskys/KVKCalendar#59]
Hello, I want to change position of date list as attached screen short please guide me on how to achieve that design.
![Screenshot 2020-03-17 at 2 38 05 PM](https://user-images.githubusercontent.com/28212734/76840543-668d3980-685d-11ea-8ea3-efbe9e1e96d3.png)

**Comment by kvyatkovskys** [comment]
Hi)
Hmmm, I would use the `UITableView` with custom cell
