### ISSUE TITLE
How do I get current date

### ISSUE THREAD

**Issue by bitdelve** [kvyatkovskys/KVKCalendar#60]
Is it possible to get the current date on the calendar? Like when I am on the week view, can I get at least the starting date? Or can I get the date range? Like March 15-21?

**Comment by kvyatkovskys** [comment]
I’ll add an additional method to protocol to get current events and dates. 
In next release

**Comment by kvyatkovskys** [comment]
Added new method `func didDisplayEvents(_ events: [Event], dates: [Date?])` to `CalendarDelegate` to v0.2.8
