### ISSUE TITLE
Calendar scrolls up but never down

### ISSUE THREAD

**Issue by FranciscoBaiao** [kvyatkovskys/KVKCalendar#65]
When moving an event, the calendar scrolls up but not down.

**Comment by kvyatkovskys** [comment]
You can disable this`timeline.scrollToCurrentHour = false`

**Comment by FranciscoBaiao** [comment]
No, that's not the issue... the issue is when your are changing an event hour by moving it ... if you go close the top of calendar it will scroll, but if you get the event close bottom of calendar doesn't scroll down.

**Comment by FranciscoBaiao** [comment]
I've been doing some tests... you can try making 
"else if (point.y + scrollView.bounds.height/5) > (scrollView.contentOffset.y + scrollView.bounds.height), (point.y + eventPreviewSize.height) <= scrollView.contentSize.height " 
for the scroll down condition

**Comment by kvyatkovskys** [comment]
Can you create a PR?) I’ll check.
