### ISSUE TITLE
Header and Events Animations

### ISSUE THREAD

**Issue by JPSantosN** [kvyatkovskys/KVKCalendar#67]
Hello, first of all, the library is excellent. 

My question is:

In the week view, when I horizontally scroll the calendar view (events), the header (mon, tue, wed ..) moves together with the events (horizontal animation) and changes to the next or previous week. But when I horizontally scroll header, the events don't have animation. Is there an option to move the events when the header is scrolling (same animation when events view is scrolling) ?.

The question is because I have recurring events, so without the animation (when scrolling the header), the events do not make the animation of the week change.

Thank you.

**Comment by kvyatkovskys** [comment]
Hello and thank you 😊 

This’s not a bug) I disabled this feature, cos I need to improve the scrolling of header view. I’ll add this in the next release.

**Comment by JPSantosN** [comment]
Thank you. I will be waiting for the next release.
