### ISSUE TITLE
EventPageView width calculation is impractical 

### ISSUE THREAD

**Issue by SjorsSchijff** [kvyatkovskys/KVKCalendar#70]
When adding a very long event that overlaps with multiple other events the library comes up with very strange widths for the EventPageViews (see attached image).

<img width="398" alt="EventPageView Width" src="https://user-images.githubusercontent.com/11303051/84678999-075cc500-af31-11ea-9c1c-efe54a1ef34a.png">

Could you please make this behaviour modifiable or the function that calculates the page width overridable?

Kind regards,
Sjors

**Comment by SjorsSchijff** [comment]
I think the problem arises from:
https://github.com/kvyatkovskys/KVKCalendar/blob/0c51c2bca4923336a7972049a837347bb6b7d404/KVKCalendar/Classes/TimelineView.swift#L235
and
https://github.com/kvyatkovskys/KVKCalendar/blob/0c51c2bca4923336a7972049a837347bb6b7d404/KVKCalendar/Classes/TimelineView.swift#L239

I think you will want to determine the highest number of simultaneous events for that day and adjust the width to that number. I suppose something in the line of `newCountsEvents[idx].count = max(newCountsEvents[idx].children.filter { event.start.timeIntervalSince1970 >= $0.start && event.end.timeIntervalSince1970 <= $0.end }.count + 1, newCountsEvents[idx].count)` would increment the count taking into account its siblings.

**Comment by kvyatkovskys** [comment]
> I think the problem arises from:
> 
> https://github.com/kvyatkovskys/KVKCalendar/blob/0c51c2bca4923336a7972049a837347bb6b7d404/KVKCalendar/Classes/TimelineView.swift#L235
> 
> and
> 
> https://github.com/kvyatkovskys/KVKCalendar/blob/0c51c2bca4923336a7972049a837347bb6b7d404/KVKCalendar/Classes/TimelineView.swift#L239
> 
> 
> 
> I think you will want to determine the highest number of simultaneous events for that day and adjust the width to that number. I suppose something in the line of `newCountsEvents[idx].count = max(newCountsEvents[idx].children.filter { event.start.timeIntervalSince1970 >= $0.start && event.end.timeIntervalSince1970 <= $0.end }.count + 1, newCountsEvents[idx].count)` would increment the count taking into account its siblings.

I’ll try to fix it in the next version. 
Thanks)
