### ISSUE TITLE
willDisplayDate documented

### ISSUE THREAD

**Issue by justdan0227** [kvyatkovskys/KVKCalendar#71]
Thanks for the update. Will you also update the documentation to explain willDisplayDate ?

**Comment by kvyatkovskys** [comment]
Sure, I’ll update in next release.

**Comment by justdan0227** [comment]
did you get a chance to document this?  Thanks!

**Comment by kvyatkovskys** [comment]
> did you get a chance to document this? Thanks!

yes, I did

**Comment by justdan0227** [comment]
oh so sorry.. I can't find willDisplayDate anywhere in the Wiki?
