### ISSUE TITLE
Month horizontal scroll

### ISSUE THREAD

**Issue by bellonigiulia** [kvyatkovskys/KVKCalendar#72]
I needed the month scroll to be horizontal so I set the scrollDirection to .horizontal in MonthStyle and it works. The problem is that the days now are displayed in vertical.

<img width="403" alt="Schermata 2020-06-19 alle 16 34 36" src="https://user-images.githubusercontent.com/40742792/85144562-9c223400-b24b-11ea-98f6-6a3c7a7a47c3.png">

Also, opening the view the current date is hidden and it appears only after the first scroll.

**Comment by kvyatkovskys** [comment]
hello, 

This functionality is not implemented in the project and the property `scrollDirection` is closed.

**Comment by giuliabelloni** [comment]
Hi, is there any workaround to achieve a similar result?
