### ISSUE TITLE
Customizable EventPageView through new func in protocol

### ISSUE THREAD

**Issue by azpery** [kvyatkovskys/KVKCalendar#74]
Hi, 

First, thank you for your work, it is beautiful and well coded. 

Though, I'd like to know if it is possible to add a function in a protocol so we could customize the EventPageViews. 

For example I'd like to add labels in the event view. And if I'm right, the protocol you expose does not support those kind of purpose. 

In a UITableViewController there is this method : func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell  that allows us to return a customizable view.

I can give it a try and make a pull request.

**Comment by kvyatkovskys** [comment]
Hello and thank you🙂

I created a branch `feature/v_0.3.4` you can try this feature. 

So, you need create a new class `class CustomEventView: EventViewGeneral` subclass from `EventViewGeneral` and call this method `func willDisplayEvent()` in your controller to create a new custom view for event.

I plan to release v0.3.4 on this week, if you want you can improve this feature (create a PR to this branch).

**Comment by azpery** [comment]
Thank you very much for this improvement, I reviewed your code and it looks great. I try this today and if I find some bugs I will make a PR to fix them :)

**Comment by azpery** [comment]
Hello Sergei, 

I've made a PR for a new enhancement aiming to enable/disable autoscroll when reloading data because, I load datas asynchronously so I'd like the timeline view to stay still while I reload it. 

Also, i've tested the new func, it suits perfectly what I need 🥇 

Thanks, bye

**Comment by kvyatkovskys** [comment]
Hello Robin,

Cool🙂 I leave a comment to PR and I added a minor fixes for your autoscroll problem.
