### ISSUE TITLE
Multiple day event

### ISSUE THREAD

**Issue by vikaspatidar805** [kvyatkovskys/KVKCalendar#77]
for example start date from 2020-07-19 at 08:30 and end date 2020-07-21 at 2:52, so how can show 3 days event 
 {
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c745",
            "end": "2020-07-21T12:52:00+03:00",
            "id": "0",
            "start": "2020-07-19T08:30
![Simulator Screen Shot - iPhone 11 - 2020-07-22 at 10 46 23](https://user-images.githubusercontent.com/53084884/88137255-caa77c00-cc08-11ea-9c16-993cabf8aefc.png)
:00+03:00",
          
            "text_color": "#000000",
            "title": "All day event number 2",
            "files": ["file"]
        }
![Simulator Screen Shot - iPhone 11 - 2020-07-22 at 10 46 23](https://user-images.githubusercontent.com/53084884/88138361-23781400-cc0b-11ea-9a2d-cadbf71b45b8.png)

**Comment by vikaspatidar805** [comment]
{
            "all_day": 0,
            "border_color": "#FFFFFF",
            "color": "#12c745",
            "end": "2020-07-21T12:52:00+03:00",
            "id": "0",
            "start": "2020-07-19T08:30
![Simulator Screen Shot - iPhone 11 - 2020-07-22 at 10 46 23](https://user-images.githubusercontent.com/53084884/88137255-caa77c00-cc08-11ea-9c16-993cabf8aefc.png)
:00+03:00",
          
            "text_color": "#000000",
            "title": "All day event number 2",
            "files": ["file"]
        }

**Comment by kvyatkovskys** [comment]
🤔 I guess, this is a bug 🐜

**Comment by vikaspatidar805** [comment]
> 🤔 I guess, this is a bug 🐜

can you please fix it?.
Thanks in advance

**Comment by kvyatkovskys** [comment]
sure, I'll try but it won't be quick
