### ISSUE TITLE
Custom Xib support for events ?

### ISSUE THREAD

**Issue by harshith30** [kvyatkovskys/KVKCalendar#79]
Hi @kvyatkovskys , First thank you for this great library.

Is it possible  to customise the events view, to achieve the below design ?

If yes please let me know.

**Comment by kvyatkovskys** [comment]
Hello and thx 🙂

Yes, it possible. You can try this functionality in a branch `feature/v_0.3.4`. Also I updated a README and you can read how to implement a custom view. Anyway, I plan to release a new version tomorrow.

**Comment by harshith30** [comment]
That's great , looking forward to work on those changes.

**Comment by harshith30** [comment]
Hi @kvyatkovskys ,

Can you also add support for Storyboard if possible during your next release please.

**Comment by kvyatkovskys** [comment]
🤔 I guess, you can create a class of `EventViewGeneral` -> add view in storyboard -> select your class in storyboard view settings

**Comment by harshith30** [comment]
Got it, and implemented it .


![Screenshot 2020-07-24 at 5 04 29 PM](https://user-images.githubusercontent.com/7028737/88387259-bd88b980-cdcf-11ea-9e48-77680bdb8611.png)
