### ISSUE TITLE
How to hide Header 

### ISSUE THREAD

**Issue by harshith30** [kvyatkovskys/KVKCalendar#80]
Hi @kvyatkovskys ,

Can we hide the header view, if yes where should i be looking to make those changes. 
I want only the events part to be visible, as I'm planning to show events for only one day.

![Screenshot 2020-07-24 at 3 27 28 PM](https://user-images.githubusercontent.com/7028737/88380550-63352c00-cdc2-11ea-8345-1fec0e791900.png)

**Comment by kvyatkovskys** [comment]
Good question. At present, no... need to add a new property to `HeaderViewStyle` and check this in `DayView`.

**Comment by harshith30** [comment]
Hi, I tried to change the height of the header view and set it to 0 for both "scrollHeaderDay" and "topBackgroundView" in the DayViewCalendar file, but it not change anything in the actual design.

If you don't mind, can you pls let me know exactly where i should be making the changes in the file.



![Screenshot 2020-07-24 at 6 03 44 PM](https://user-images.githubusercontent.com/7028737/88393609-8d471800-cddb-11ea-8df3-0702cbdf322a.png)

**Comment by kvyatkovskys** [comment]
Probably need to add a new property to `Style`. I'll take a look today.

**Comment by kvyatkovskys** [comment]
@harshith30 check this property `public var isHidden: Bool = false` in `HeaderScrollStyle`....
added to `feature/v_0.3.4`
![Simulator Screen Shot - iPhone 11 - 2020-07-24 at 20 13 59](https://user-images.githubusercontent.com/8233076/88417532-c1760500-cdea-11ea-93bd-8496196865c9.png)

**Comment by harshith30** [comment]
Got it. thanks a lot for providing this feature.

Looking forward for the release.

**Comment by kvyatkovskys** [comment]
Released a version 0.3.4

**Comment by developerfromjokela** [comment]
The boolean is not working.
in swiftui, i set         calendar.style.headerScroll.isHidden = true
but it's still showing up.


I used example swiftui from readme.

**Comment by kvyatkovskys** [comment]
Will check, thx!

**Comment by kvyatkovskys** [comment]
can you check this branch `feature/v_0.6.5`? I could not reproduce this issue. @developerfromjokela
