### ISSUE TITLE
How can i load calendar view size dynamic

### ISSUE THREAD

**Issue by beladiya** [kvyatkovskys/KVKCalendar#81]
I create calendar view and set its frame . In that width is 300. On button tap i want to change calendar view width 500.
I reassign new frame with 500 width but calendar view month cell and header view consist with 300 width. I want to make it dynamic width after creating calendar view object
![Screenshot 2020-07-25 at 5 11 44 PM](https://user-images.githubusercontent.com/13200570/88456268-f3927000-ce99-11ea-9d94-9086075edcdc.png)

**Comment by kvyatkovskys** [comment]
Hello

You need to use this method `calendarView.reloadFrame(frame)`

**Comment by beladiya** [comment]
ok it's worked. Thank you
