### ISSUE TITLE
ScrollDirection for Month Calendar is limited to vertical.

### ISSUE THREAD

**Issue by pwnSmithers** [kvyatkovskys/KVKCalendar#86]
var scrollDirection: UICollectionView.ScrollDirection = .vertical

scrollDirection inside MonthStyle is limited to vertical. Tried finding ways to set it to Horizontal but failed. the scroll directionVariable is not public so I can't access it.

could we make scrollDirection public?

**Comment by kvyatkovskys** [comment]
Hello 🙂

This functionality hasn't yet been implemented. When I add horizontal scroll feature, I open this property.

**Comment by pwnSmithers** [comment]
Thanks for the response, I appreciate it. Is there any possible work around I can implement?

**Comment by kvyatkovskys** [comment]
I plan to add this feature in the next release. If you want you can create a PR and implement a horizontal scrolling. 🙂
For month

**Comment by pwnstarSmithy** [comment]
Alright, let me schedule this for next week :)
I'm also trying to find a work around for not displaying the EventViewer in iPad view, currently its forcefully displaying the eventView in the Dayview on ipad. Is there a way i could turn it on and off? I can create a PR for this too, otherwise since it's a private method that initilizes TimelineView in the dayView, i can't increase the timeline frame width as it's divided by 2 on the ipad :(.

**Comment by pwnSmithers** [comment]
okay cool, let me schedule this for next week. Is there also no way for me to change the TimelineView frame width inside DayView for iPad? as it's set to only take .5 of the screen and the rest for the event Viewer. is there a way for me to not display the eventViewer on iPad?

**Comment by kvyatkovskys** [comment]
Try to change this property `public var widthEventViewer: CGFloat = 0` Timeline style.

**Comment by pwnSmithers** [comment]
Thanks, that worked. I've failed to set the timeZone of the timeline. I want the current Time to display time in a different timeZone coming from the server instead of the user's phone.How can I go about this?

**Comment by kvyatkovskys** [comment]
> Thanks, that worked. I've failed to set the timeZone of the timeline. I want the current Time to display time in a different timeZone coming from the server instead of the user's phone.How can I go about this?

Sorry I missed your question. Is still relevant?
