### ISSUE TITLE
Event is not displayed well when date format is changed in iPhone

### ISSUE THREAD

**Issue by AlexandraMedrano** [kvyatkovskys/KVKCalendar#87]
Hi, 

I've been testing the example using this pod. It is really amazing and I didn't find this error until I began to test it in a actual cellphone. 
I only tested on iPhone 7, 8 and 11. What happens is that when I have my cellphone configured with 24-hour format, all events are display as follows:
![IMG_1435](https://user-images.githubusercontent.com/16809936/92177904-a1c8f800-edfe-11ea-8e07-a0500393cef5.PNG)

However, as soon as I change to 12-hour format, an error occurs and the events are displayed as follows: 
![IMG_1436](https://user-images.githubusercontent.com/16809936/92177963-bf965d00-edfe-11ea-944e-edfd2d71facc.PNG)

I really would appreciate if you could guide me trough this problem.

**Comment by kvyatkovskys** [comment]
Hello 🙂
Could you update a library to actual version 0.3.6? And repeat test 🙂

**Comment by AlexandraMedrano** [comment]
Hi,

I updated the library and tested and when the iPhone is set to 24-hour format, it shows the events as follows:
![IMG_48EC2C4E9BB0-1](https://user-images.githubusercontent.com/16809936/92256193-a50cc400-ee90-11ea-9e6d-5f4d10672eba.jpeg)

and when is set to 12-hour format, it raises the following error:
![image](https://user-images.githubusercontent.com/16809936/92312612-93eeb080-ef7f-11ea-83fb-27bc08e887bb.png)

**Comment by kvyatkovskys** [comment]
This is not an error 🙂`Event number 16` has an end date on next day (15 December).

**Comment by AlexandraMedrano** [comment]
I copied the same image in the previous comment by mistake. I've updated the comment with the screenshot of actual error.

**Comment by kvyatkovskys** [comment]
🤔 thx for the response.
