### ISSUE TITLE
Add Delegate Method for when user scrolls to a new date range.

### ISSUE THREAD

**Issue by chrisvoronin** [kvyatkovskys/KVKCalendar#88]
When we are using the calendar we don't load all events at once.  But only for specific time interval, since we have a monthly view or weekly view.

Would be great if there was a delegate method that let us know when user has scrolled the calendar to a new month so that we could dynamically load events for the new month.  Since we do let users scroll infinitely.

Also an option to show titles for events instead of dots on monthly view.

**Comment by kvyatkovskys** [comment]
🤔 good point. I will add these  enhancements in the next release.

**Comment by kvyatkovskys** [comment]
I've idea... I can add ability to load events +/- one month/week from current displaying events for week/month view
