### ISSUE TITLE
How to change orange bg color

### ISSUE THREAD

**Issue by Bloueco** [kvyatkovskys/KVKCalendar#93]
I can't seem to find a way to remove the orange background colour that appears from todays date + 10 days. Please help!
<img width="174" alt="Screenshot 2020-09-17 at 15 37 04" src="https://user-images.githubusercontent.com/36682810/93486050-a7910400-f8fb-11ea-8a24-e1b2f76fa34d.png">

**Comment by kvyatkovskys** [comment]
Hello 🙂

Just delete this function `func willDisplayDate(_ date: Date?, events: [Event]) -> DateStyle?` or return `nil`

**Comment by Bloueco** [comment]
Thankyou so much

**Comment by kvyatkovskys** [comment]
YW 😉
